### ISSUE TITLE
Can't edit/open contacts

### ISSUE THREAD

**Issue by TomJansen** [Chooloo/koler#106]
When clicking a contact and then the edit button or info button, it does not work.

**To Reproduce**
1. Click on a contact
2. Click on the edit button or info button
4. See error: cant open contact when editing or contact does not exist when clicking info button

**Expected behavior**
Contact edit screen (in your contact app of choice) should open

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 8
-  Koler: v0.5.6
 
**Additional context**
Does not work with the Samsung contacts app nor with the Google contacts app

**Comment by Oymate** [comment]
Mine opens from the right then closes back to left again.
Redmi note 7

**Comment by roeiedri** [comment]
The new Koler version (in development) fixes that
