### ISSUE TITLE
No on GPlay more

### ISSUE THREAD

**Issue by 532910** [Chooloo/koler#107]
GPlay says the URL is wrong pressing `get in google play` button in readme.

**Comment by roeiedri** [comment]
Yeah i removed the app, no support and it has bugs
Ill upload it once ill fix most of it

**Comment by 532910** [comment]
This way the button also should be removed.

**Comment by 532910** [comment]
Still no app on gplay and button exists. Button should be removed or app added to gplay.

**Comment by roeiedri** [comment]
Yeah im stupid
Removed the button :)

**Comment by 532910** [comment]
It's still in [README](https://github.com/Chooloo/koler/blob/master/README.md)
