### ISSUE TITLE
[Glitch Report] Some Contacts are being shown twice

### ISSUE THREAD

**Issue by TuxKruger** [Chooloo/koler#109]
**Bug Description**
It is more like a glitch not a bug. I guess the title of the issue is enough to explain textually, here's a screenshot
https://paste.pics/69f4a29bcdf2baaafe56b89433ca7815

**To Reproduce**
1. Go to Contacts tab in Koler

**Expected behavior**
It should show a contact only once instead of showing it twice. I have checked my Contacts app too, I only see a contact once in there not twice or more time.

**Device Details**
 - Device: Redmi Note 9S
 - OS: Lineage OS 18 Android 11

**Comment by blu-bots619** [comment]
I have the same problem also..

**Comment by wenngle** [comment]
I am also experiencing the issue
