### ISSUE TITLE
Incoming and outgoing call UI are inappropriate

### ISSUE THREAD

**Issue by ghost** [Chooloo/koler#115]
**Describe the bug**
Incoming and outgoing call UI(layouts) are in a incorrect position. 

**To Reproduce**
1. Taking incoming call
2. Ongoing call also

**Screenshots**
![Screenshot_20201110-105732](https://user-images.githubusercontent.com/74180523/98680259-0e112c00-2359-11eb-9408-9378f4159c95.png)
![Screenshot_20201110-105651](https://user-images.githubusercontent.com/74180523/98680264-10738600-2359-11eb-9f53-61e8cf9cff23.png)

**Smartphone (please complete the following information):**
 - Device: Lava R1
 - OS: Android 6
 
**Additional context**
Please fix this issue because I love this app and I think that the problem were causing due to screen resolution(my phone)

**Comment by zhirzh** [comment]
i am guessing the issue here is with the "end call" button overlapping with "dialpad" and "plus" buttons
this should be fixed in latest release

**Comment by roeiedri** [comment]
The new Koler version will have a different new UI
