### ISSUE TITLE
search text does not clear up when switching screens

### ISSUE THREAD

**Issue by zhirzh** [Chooloo/koler#121]
**Describe the bug**
when searching for a contact or call log by name (in search bar) or number (in dialpad), the text doesn't clear up when switching screens. In case of dialpad, it also doesn't clear up when the number is called.

**To Reproduce**
1. type a number in dialpad and call it
1. check dialpad to see if the typed number is still there

**Comment by roeiedri** [comment]
Im working on a new version of koler from scratch, will take some time, its hard with no finanicial support
I this issue still happens in the next version, open it again
