### ISSUE TITLE
Implementing Block Phone Numbers (Black List)

### ISSUE THREAD

**Issue by qw123wh** [Chooloo/koler#123]
Add ability to block unwanted calls, maybe this can help you

https://source.android.com/devices/tech/connect/block-numbers?hl=en#examples-and-source

**Comment by roeiedri** [comment]
I added a preference which leads to the phone blocked numbers manager
Is that a good solution for you?

**Comment by qw123wh** [comment]
Is there the possibility to add other numbers directly from koler to the manager of blocked numbers from the phone?  Or do you have to add them manually?

**Comment by roeiedri** [comment]
Added block button for contacts and numbers

**Comment by NastyFlytrap** [comment]
> Added block button for contacts and numbers

Where is this button?

**Comment by minus21grams** [comment]
> > Added block button for contacts and numbers
> 
> Where is this button?

Couldn’t find the button either 🤔
Every time I get a spam or suspicious call, I have to set Android’s stock phone app as default in order to blacklist the fraudulent number...
