### ISSUE TITLE
Excel tab hidden by default 

### ISSUE THREAD

**Issue by mizzunet** [Chooloo/koler#126]
**Is your feature request related to a problem? Please describe.**
Well, Excel tab is unnecessary for most users, and it can not be hidden anyway.
**Describe the solution you'd like**
So I think its a better, it to be disabled by default and give a toggle for showing in Settings in case anyone wants.
**Additional context**
This also make it simple

**Comment by roeiedri** [comment]
The excel tab will be removed in the new Koler, yeah honestly no one needs it
