### ISSUE TITLE
Google Pixel 3XL - Speakerphone and numeric dialpad

### ISSUE THREAD

**Issue by adrenatek** [Chooloo/koler#129]
**Describe the bug**
Neither work as would be expected. Dialer does not transmit tones to called party and speakerphone button mutes speaker instead of making it louder. 

**To Reproduce**
Use as normal

**Expected behavior**
Correct operation

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3XL
 - OS: Android 10
 
**Additional context**
SUSPICION THAT THE DEFAULT ANDROID / GOOGLE DIALER MAY HAVE SOME OF THIS INFORMATION MAPPED IN A WAY THAT IS NOT CONSIDERED THE OPEN SOURCE DEFAULT MAY NEED TO ADJUST ACCORDINGLY

**Comment by adrenatek** [comment]
I really like this dialer. I hope this can be fixed. IDK how to code lol

**Comment by roeiedri** [comment]
Please reopen if issue appears in the new version
