### ISSUE TITLE
dialpad not working

### ISSUE THREAD

**Issue by zer0fl0w** [Chooloo/koler#135]
v1.0.0 beta
oneplus 8t
oxygen os 11 based on android 11

after opening dialpad pressing any button will crash and freeze koler completly.

**Comment by roeiedri** [comment]
Oh oops
My bad ill push a fix asap

**Comment by roeiedri** [comment]
Fixed in latest version

**Comment by roeiedri** [comment]
Look at the latest release

**Comment by zer0fl0w** [comment]
thanks for the quick fix. works now. thanks.
