### ISSUE TITLE
call history missing

### ISSUE THREAD

**Issue by zer0fl0w** [Chooloo/koler#136]
not really an issue per se, but missing call history i cant see when i have more than one missed called
who tried to call me.

one missed call shows notification with caller. 2 or more calls shows only notification with number of missed calls but without the possibilty the see caller name.

so +1 for call history. nice app so far.

**Comment by roeiedri** [comment]
Sorry I didn't fully understand, Koler doesn't post notifications regarding missed calls so you're talking about your native dialer

**Comment by zer0fl0w** [comment]
sorry for not making myself clear.

also i just found 'recents' by swiping left on 'contacts'-screen...

that was what i was missing, when i said 'call history' before.

so its there and i can die in peace.

**Comment by roeiedri** [comment]
Haha yeah i need to make that more obvious
