### ISSUE TITLE
Status bar invisible

### ISSUE THREAD

**Issue by gokulraam** [Chooloo/koler#144]
When the app is opened, phone status bar is invisible. 

Device details. 
 - Device: ASUS_X00TD
 - OS: Android 9

**Comment by mizzunet** [comment]
> When the app is opened, phone status bar is invisible.
> 
> Device details.
> 
> * Device: ASUS_X00TD
> * OS: Android 9

Is it invisible or are the icons are black? In mine, it's black while background colour is also a darken colour. 
![Screenshot_20210331-155654_1](https://user-images.githubusercontent.com/10193999/113130500-c58bd980-9239-11eb-8333-31daf1ea56aa.png)

**Comment by gokulraam** [comment]
Yeah the icons are black so its not visible in dark mode.

**Comment by roeiedri** [comment]
Oh yeah i noticed that too
Thanks ill push a fix
