### ISSUE TITLE
Contact details bug in recents. 

### ISSUE THREAD

**Issue by gokulraam** [Chooloo/koler#145]
Viewing saved contact details is not the same in contacts view and call history view, in call history view when details is opened at bottom it doesn't even show name of the saved contacts. 

Applicantion version v1.0.2

**Comment by roeiedri** [comment]
Can you be more specific?

**Comment by gokulraam** [comment]
Added screenshot but just hided info details in yellow.
![contacts](https://user-images.githubusercontent.com/40225391/113095556-29cf7e80-91e3-11eb-87c8-31663fb9f8fd.png)
![recents](https://user-images.githubusercontent.com/40225391/113095560-2c31d880-91e3-11eb-8ad3-5effde3157d9.png)

**Comment by mizzunet** [comment]
Don't understand what did you mean. No issue regarding that here.

**Comment by gokulraam** [comment]
When clicking on any saved contact in call history / recent view the name of saved contact  and edit icon does not show while it does when clicking on a contact in contacts view.

**Comment by mizzunet** [comment]
> When clicking on any saved contact in call history / recent view the name of saved contact and edit icon does not show while it does when clicking on a contact in contacts view.

So, you want to edit a saved contact from Recent tab, don't you? Why would you do that? It's not that needed I believe. You may edit it from Contacts tab. BTW, you can add unsaved contact thought

**Comment by gokulraam** [comment]
Don’t always need to search in contacts and do the same thing when this can be done in recent view itself and UI will be consistent between the two.

**Comment by roeiedri** [comment]
It beats the purpose of the recents
The bottom screen that opens up on a recent click, represents a recent call and not a contact
What i can do is maybe add a button that opens up the contact but editing is reserved for the contact screen itself

**Comment by gokulraam** [comment]
Makes sense and the button could be a sort of shortcut to contact and opening call details doesn't reliably show up saved contact name it shows blank or the number. Screenshot attached above(second) shows it as blank.
