### ISSUE TITLE
Not able to edit contacts

### ISSUE THREAD

**Issue by gokulraam** [Chooloo/koler#146]
When edit icon clicked on contact details, it opens  a view that shows view only. Atleast can redirect to default contacts app.

**Comment by roeiedri** [comment]
Not sure what you mean, can you send a screenshot? Because for me it works

**Comment by gokulraam** [comment]
Sorry about this issue, this actually happens for numbers that are prebuilt that comes with sim such as network care/service numbers that are not editable. This isnt an issue but normal behavior for these default numbers. Didn't seen this view before because the apps used before only open contact view where there will be/wont be edit contact button and doesn't open edit contact directly.
