### ISSUE TITLE
a way/button to disable the animations

### ISSUE THREAD

**Issue by DigitalNXZ** [Chooloo/koler#153]
**Is your feature request related to a problem? Please describe.**
- the animation makes me a bit sick. (important)
- would it be possible for a compact mode? the whole new redesign/work is hella beautiful but there is to much padding to my liking. (not important)

**Describe the solution you'd like**
- a button to deactivate the animations
- and would it be possible to copy the number to clipboard when on the call/edit/delete/message menu? by clicking on the number for a second?

**Describe alternatives you've considered**

**Additional context**

**Comment by roeiedri** [comment]
The copy feature is currently not possible as clicking on the number currently initiates a call to that number
