### ISSUE TITLE
Tint design suggestion

### ISSUE THREAD

**Issue by mizzunet** [Chooloo/koler#157]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It's just my opinion based on my point of view. The current UI is already awesome. Though I'm making an opinio is that,
The tint button would look better if the the icons/texts are darker than backgroud colour, like these icons
![Screenshot_20210401-130328](https://user-images.githubusercontent.com/10193999/113259366-abf69a80-92ea-11eb-9732-9e1ad3449266.png)
than lighter than backgroud colour 
![Screenshot_20210401-130416_1_1](https://user-images.githubusercontent.com/10193999/113259919-4c4cbf00-92eb-11eb-9e6d-edbdbd6029b8.png)
![Screenshot_20210401-130416_1](https://user-images.githubusercontent.com/10193999/113259938-5078dc80-92eb-11eb-8ace-646844c91e83.png)

 

I wish I knew coding, I would contribute myself :(

**Comment by roeiedri** [comment]
I actually tried that at first and thought this looks a bit darker (which
is better because its in dark mode)
And i change it to your suggestion itll make everything lighter looking
But ill see if can make that look good :)
