### ISSUE TITLE
USSD codes aren't working

### ISSUE THREAD

**Issue by mizzunet** [Chooloo/koler#164]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open dialpad
2. Call any USSD codes, *123# for ex.

### Actual behaviour

It calls the number of the code rather than requesting retrieve USSD

### Expected behavior

Show something like this
![Screenshot_20210403-211837 png](https://user-images.githubusercontent.com/10193999/113483672-452bd980-94c2-11eb-8996-86b329547bbb.jpg)
then show details of it

### Device info

 - Android version/Custom ROM version: 11, RevengeOS
 - Device model: OnePlus 5

**Comment by roeiedri** [comment]
If the number has a * in the beginning and # in the end, that's enough to know it's a ussd code?
What do you think?

**Comment by mizzunet** [comment]
> If the number has a * in the beginning and # in the end, that's enough to know it's a ussd code?
> What do you think?

Yes, I believe

**Comment by O-DoC** [comment]
Useful for network operations in 'occidental countries'.
Mandatory in 'not occidental countries' like India or Africa continent like lot of services go through ussd due to lack of stable data or cost for connection.

**Comment by fossfann** [comment]
I can confirm USSD codes are still not working in 1.0.9 version. MIUI 12 stock ROM and not rooted.

**Comment by fossfann** [comment]
> Useful for network operations in 'occidental countries'.
> Mandatory in 'not occidental countries' like India or Africa continent like lot of services go through ussd due to lack of stable data or cost for connection.

This is so useful because i am changing preferred network type by *#*#4636#*#* and this is so important for me.

**Comment by roeiedri** [comment]
Already fixed
