### ISSUE TITLE
Call history popup UI suggestion 

### ISSUE THREAD

**Issue by gokulraam** [Chooloo/koler#165]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Call history popup shows big icon at the middle which is not good looking. It would be good to show at the right side of the name.

#### Is your feature request related to a problem? Please describe it

There isn’t much problem but the popup is much bigger.

#### How will you/everyone benefit from this feature?

The UI might be more compact.

**Comment by roeiedri** [comment]
At first the icon was on the right but that a ui chnage i think looks good.
Makes this part look a bit less compact which is good considering the whole app is very compact.
