### ISSUE TITLE
Call history issue

### ISSUE THREAD

**Issue by gokulraam** [Chooloo/koler#167]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1.Go to recents view. 
2. Click on an history. 
3. History grouped wrongly by date. 

### Actual behaviour

Calls that were made yesterday shows in today. Screenshot attached shows a yellow mark on which it is clicked. It shows in today instead of yesterday. 

### Expected behavior

History show correctly for the mentioned dates. 

### Screenshots/Screen recordings

![Screenshot_20210404-093544](https://user-images.githubusercontent.com/40225391/113498324-71178100-94fb-11eb-87be-acdfac4e0085.png)

### Device info

 - Android version/Custom ROM version: 9

**Comment by gokulraam** [comment]
The issue occuring in version 1.0.5 downloaded from izzyondroid fdroid repo.

![issue2](https://user-images.githubusercontent.com/40225391/114494667-453b8000-9c0c-11eb-8476-e7d13c794b8b.jpg)

@roeiedri

**Comment by roeiedri** [comment]
🙂🔫
