### ISSUE TITLE
Incoming call UI in recents after missed

### ISSUE THREAD

**Issue by gokulraam** [Chooloo/koler#169]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1.  Received an incoming call that is missed. 
2. Incoming call UI remains in app recents screen. 

### Actual behaviour

Incoming call UI remains in app recents section. 

### Expected behavior

Incoming call UI should not remain in app recents after missed. 

### Device info

 - Android version/Custom ROM version: 9
 - Device model:  Asus X00TD

**Comment by gokulraam** [comment]
Issue still reproducible with version 1.0.5.

![issue](https://user-images.githubusercontent.com/40225391/114494118-4b7d2c80-9c0b-11eb-80a7-ab73b7b77c80.jpg)

@roeiedri

**Comment by roeiedri** [comment]
Reopen if still happens in latest version (ill upload it soon)
