### ISSUE TITLE
Unable to respons when click on ( + ) option while calling

### ISSUE THREAD

**Issue by lushohammy** [Chooloo/koler#17]
#### Expected behavior
Click or press on (+) option to join another caller while calling 

#### Actual behavior
i cant join another caller when i press on (+) option

#### How to reproduce
* Call someone 
* then press (+) option 
* and see the bug

#### Operating system 
* App version:v 0.2.8
* Android v8.1.0 OPMI

#### Recording Of The Bug
https://youtu.be/usECSq_avVg

**Comment by roeiedri** [comment]
This is a feature we haven't added yet.
Be sure we will

**Comment by girubhai** [comment]
@roeiedri Thanks for such a great library.

Is there any date to include conference call?

**Comment by aZyreTech** [comment]
Is this feature is added or not ?

**Comment by roeiedri** [comment]
Not yet, it's not a priority for us but we see that this feature is
requested so we will do our best to release it in the next update
