### ISSUE TITLE
Ask to make Koler as default dialer

### ISSUE THREAD

**Issue by mizzunet** [Chooloo/koler#171]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Show a message while opening, as if to make Koler as default dialer

#### Is your feature request related to a problem? Please describe it

No

#### How will you/everyone benefit from this feature?

Otherwise have to get to Settings for changing it.

**Comment by roeiedri** [comment]
It should already do that its a bug :)

**Comment by mizzunet** [comment]
> It should already do that its a bug :)

Oh
