### ISSUE TITLE
Denied recents show 0 duration

### ISSUE THREAD

**Issue by roeiedri** [Chooloo/koler#173]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to recents
2. Press on a denied call
3. See duration string

### Actual behaviour

A denied call has a duration string of "0 min 0 sec"

### Expected behavior

Denied calls shouldn't show duration string

**Comment by gokulraam** [comment]
It also applies to missed calls, right?

**Comment by roeiedri** [comment]
Yes
