### ISSUE TITLE
Inappropriate animation

### ISSUE THREAD

**Issue by gokulraam** [Chooloo/koler#174]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Type in dialpad. 
2. Remove numbers in dialpad. 
3. See animation when suggestions are being removed. 

### Actual behaviour

Inappropriate animation when suggestions are removed in dialpad. Animation hovers the numpad. 

### Expected behavior

Animation be better. 

### Device info

 - Android version/Custom ROM version: 9

**Comment by mizzunet** [comment]
Can you share a screen recording? I can't find any animation that hovers dialpad

**Comment by gokulraam** [comment]
https://user-images.githubusercontent.com/40225391/114343933-6fc70380-9b4e-11eb-889e-f04624d8320f.mp4

**Comment by roeiedri** [comment]
Added an option to disable animation

**Comment by roeiedri** [comment]
Also removed that specific animation you pointed out, also when having animations enabled.
