### ISSUE TITLE
Random images for contacts not having picture

### ISSUE THREAD

**Issue by mizzunet** [Chooloo/koler#175]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Random images for contacts which don't have picture would also look fantastic but it does require a lot of work, doesn't it?

#### Is your feature request related to a problem? Please describe it

Not at all

#### Additional context

OnePlus Dialer has this feature, 
![670504-f110971d2cd2258c0ec49357a38c2214](https://user-images.githubusercontent.com/10193999/113648949-263c6b80-96ab-11eb-9216-e0f88e26f2de.jpg)

#### How will you/everyone benefit from this feature?

This would look cool I guess, what do you think?

**Comment by DigitalNXZ** [comment]
Yes and no, a lot work for finding Pictures, but programming would be easy.
It would just pick a random Picture everytime or a picture based on the first Letter in the name so it doesnt selects it everytime random.

would be nice but I don't need it, less clutter is better for me, but not gonna lie it would give a bit more life to this app.

**Comment by mizzunet** [comment]
> Yes and no, a lot work for finding Pictures, but programming would be easy.
> It would just pick a random Picture everytime or a picture based on the first Letter in the name so it doesnt selects it everytime random.
> 
> would be nice but I don't need it, less clutter is better for me, but not gonna lie it would give a bit more life to Koler

I don't think it would necessary as well, but it's cool. And no need for actual images for this, this could some colour combo in some pattern maybe
