### ISSUE TITLE
~Feature Request

### ISSUE THREAD

**Issue by Muzammil011** [Chooloo/koler#177]
•**One click** to make call, Long press to open up the contact menu.

•Contact Menu should also show Contact number in recents.

•Long press on the contact number to Copy it.

•Swipe **down** to open up search.

•**Cannot** see or pickup call on lock screen. Have to unlock each time.

•Amoled Dark Mode

•12hr Time Format

•Better fluid ListView animation

Love Koler🖤

**Comment by DigitalNXZ** [comment]
had a similiar idea with copy number, it's nothing new but the dev may didn't understand right. he said it's impossible to do it because a click on the number calls.. but I said when you press it for a second.. well I don't know either.

When you click on a contact a small menu on the buttons shows up my idea was to press and hold on the number to copy it.

but could be problematic since it calls when you click and do not hold it :) missclicks always happen.

and why a 12 hour format.. ? your phone has already a clock ans I didnt seen a clock function in Koler.. well and if its just should show the time that's your phone provides

**Comment by Muzammil011** [comment]
> had a similiar idea with copy number, it's nothing new but the dev may didn't understand right. he said it's impossible to do it because a click on the number calls.. but I said when you press it for a second.. well I don't know either.
> 
> When you click on a contact a small menu on the buttons shows up my idea was to press and hold on the number to copy it.
> 
> but could be problematic since it calls when you click and do not hold it :) missclicks always happen.
> 
> and why a 12 hour format.. ? your phone has already a clock ans I didnt seen a clock function in Koler.. well and if its just should show the time that's your phone provides

In the recents, call history time format is 24hr. That's what i meant to say. It should follow system or be 12hr format at default.

**Comment by roeiedri** [comment]
> •**One click** to make call, Long press to open up the contact menu.
> 
> •Contact Menu should also show Contact number in recents.
> 
> •Long press on the contact number to Copy it.
> 
> •Swipe **down** to open up search.
> 
> •**Cannot** see or pickup call on lock screen. Have to unlock each time.
> 
> •Amoled Dark Mode
> 
> •12hr Time Format
> 
> •Better fluid ListView animation
> 
> Love Koler🖤

What do you mean contact menu? long click on the call button on the recent menu?

**Comment by Muzammil011** [comment]
This is the menu I'm talking about :)

Right now, Single click brings this menu up.

But it should be long press to bring that menu up. Additionally, contacts menu shows phone number. Recents menu does not show phone number.

AND Single click to make calls. That is convenient.


![Screenshot_2021-04-09-21-21-00-41_08d7bba8ac02e6565ce0f221da0e2a42.jpg](https://user-images.githubusercontent.com/82020443/114207724-51a8aa00-997a-11eb-989d-ba903d393c40.jpg)

**Comment by roeiedri** [comment]
So single click on recent will call and long click on recent will show menu
But single click on contact will show menu?

About the recent number, ive already answered on one of the issues
UX wise its not the best solution
A recent should only show name or number of no name
The contact should show number
I added a contact button on recent which are also contacts

**Comment by Muzammil011** [comment]
single click on recent will call and long click on recent will show menu But single click on contact will show menu.


 Yes that's fine.
