### ISSUE TITLE
can't call, it just flashes one time

### ISSUE THREAD

**Issue by DigitalNXZ** [Chooloo/koler#178]
Fix could be to deinstall any diff. Dialer apps that changed your Call Manager like Simple Dialer.
Suggested by @Netscaping and it worked for me.

## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'Tap on Contact'
2. Press on 'Call'
3. Swipe down to 'nothing happens'

### Actual behaviour

So the first time I tried to call someone with Koler and well it doesn't call, it just reloads the App, just a simple one-time Flash.
Yes I set it as a Default Dialer App and I'ts the newest version. 

I tried it with a number that has a + at the beginning and one without.

### Logs

04-07 20:23:57.624 D/OpenGLRenderer(21945): endAllActiveAnimators on 0x702acc2d00 (MenuPopupWindow$MenuDropDownListView) with handle 0x709d20d9c0
04-07 20:24:05.084 I/Toast   (21945): Show toast from OpPackageName:com.pluscubed.matlog, PackageName:com.pluscubed.matlog
04-07 20:24:05.407 D/OpenGLRenderer(21945): endAllActiveAnimators on 0x70351be400 (MenuPopupWindow$MenuDropDownListView) with handle 0x709d20d540
04-07 20:24:34.339 I/Toast   (21945): Show toast from OpPackageName:com.pluscubed.matlog, PackageName:com.pluscubed.matlog
04-07 20:24:34.640 D/OpenGLRenderer(21945): endAllActiveAnimators on 0x7091360200 (MenuPopupWindow$MenuDropDownListView) with handle 0x70aa556020
04-07 20:24:44.479 I/Toast   (21945): Show toast from OpPackageName:com.pluscubed.matlog, PackageName:com.pluscubed.matlog
04-07 20:24:44.779 D/OpenGLRenderer(21945): endAllActiveAnimators on 0x7091360c00 (MenuPopupWindow$MenuDropDownListView) with handle 0x709d31d600

### Device info

 - Android version/Custom ROM version: MIUI
 - Device model: Xiaomi K20/9T Pro
 
 "build.board: raphael
build.bootloader: unknown
build.brand: Xiaomi
build.cpu_abi: arm64-v8a
build.cpu_abi2: 
build.device: raphael
build.display: QKQ1.190825.002 test-keys
build.fingerprint: Xiaomi/raphael/raphael:10/QKQ1.190825.002/V12.0.5.0.QFKMIXM:user/release-keys
build.hardware: qcom
build.host: c4-miui-ota-bd083.bj
build.id: QKQ1.190825.002
build.manufacturer: Xiaomi
build.model: Mi 9T Pro
build.product: raphael
build.radio: unknown
build.serial: unknown
build.tags: release-keys
build.time: 1614135680000
build.type: user
build.user: builder
version.codename: REL
version.incremental: V12.0.5.0.QFKMIXM
version.release: 10
version.sdk_int: 29"

**Comment by roeiedri** [comment]
What version were you using?

**Comment by DigitalNXZ** [comment]
still the latest.
1.0.4

**Comment by fossfann** [comment]
> still the latest.
> 1.0.4

I had this issue too. Grant all notification and other permissions in Other Permissions section and write the result please

**Comment by DigitalNXZ** [comment]
I already tested it tested all permissions, even battery setting is on no restriction, I gave it Admin rights too, sadly Nothing happens

**Comment by DigitalNXZ** [comment]
@roeiedri here this time it logged everything, I hope its more helpful than last time, I'm sowwy!
[logcat.txt](https://github.com/Chooloo/koler/files/6342282/logcat.txt)

**Comment by Netscaping** [comment]
Do you have another dialer app ? es. simple dialer
I had the same problem but I found that the reason this happened was because I chose another app as the Call manager (es. simple dialer). When you call it asks you to choose to complete the action with the default android call management or simple dialer, I had choosen to use always simple dialer (when I first installed simple dialer) instead of the android one and that makes koler not call. I don't know how to change the default call manager but uninstalling simple dialer( the one I chose as default call manager) fixed it.

**Comment by DigitalNXZ** [comment]
@Netscaping, thanks but I think you misread something, or is there something beside the Defualt Dialer Setting?
> Actual behaviour
> So the first time I tried to call someone with Koler and well it doesn't call, it just reloads the App, just a simple one-time Flash.
> Yes -- >**I set it as a Default Dialer App** < -- and I'ts the newest version.

I have Simple Dialer for sure, but currently I set it as the default Dialer only when I need to Call someone..
Because with Koler I cannot do it.. I set Koler only as a Default Dialer when I'm testing it, because it must be set as Default.

On Xiaomi Phones it's: Settings > Apps >  Manage Apps > Buttons on Top Right Corner > Default Apps

**Comment by Netscaping** [comment]
@DigitalNXZ I didn't misread.
See, phone dialer and call manager are 2 different things. At least on my device. Try uninstalling simple dialer and see if it  works.
When you first make a call with simple dialer it asks you to choose a call manager, between android call manager and simple dialer call manager. If you choose to always use simple dialer call manager then koler breaks.  At least that's how it works on my device.
I don't know how to change the default call manager, but you don't change it by changing the default dialer.

**Comment by DigitalNXZ** [comment]
@Netscaping well, so I actually did and wow.. fr
Just deinstalling Simple Dialer fixed that s***? interesting.

**Comment by roeiedri** [comment]
I didn't know there's a difference between a call manager and the default dialer.
Are you sure there are 2 different things? maybe you just set the other app as the default dialer.
@DigitalNXZ Are you sure call manager is a thing?

**Comment by DigitalNXZ** [comment]
> I didn't know there's a difference between a call manager and the default dialer.
> Are you sure there are 2 different things? maybe you just set the other app as the default dialer.
> @DigitalNXZ Are you sure call manager is a thing?

Koler was default app, yes like @ghost said.. there is something like a call manager..  100% sure about that!

see it for yourself, install Simple Dialer.. first it asks you to set it as default and if you call someone it asks again.. i think its somethin like a forward call thing manager.. because both using Simple Dialer if you click them.. 1 stock and the other from simple dialer

**Comment by DigitalNXZ** [comment]
https://www.quora.com/What-is-com-android-server-telecom
https://developer.android.com/reference/android/telecom/package-summary

if you do a call you can decide between this here the call manager and simple dialers call manager

the thing is, koler doesn't work woth the simple dialer call manager and I don't know where you cam change it.. simply uninstalling simple dialer works fine

**Comment by roeiedri** [comment]
Still happens?
