### ISSUE TITLE
Call duration bug

### ISSUE THREAD

**Issue by mizzunet** [Chooloo/koler#183]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Let someone call you
2. Let it ring for few seconds, say 10 seconds
2. Accept the call
### Actual behaviour

Call duration includes the time of ringing as well
If call is taken after 10 sec, the durations starts from 0:10
This also happens for outgoing call
### Expected behavior

This time should only star after accepting the call(in case of incoming) or the end person takes(in case of outgoing)

### Screenshots/Screen recordings

![Screenshot_20210410-124320__01](https://user-images.githubusercontent.com/10193999/114262065-97598700-99fb-11eb-9a70-d03ce3ce44cb.png)
![Screenshot_20210410-124325__01](https://user-images.githubusercontent.com/10193999/114262066-99234a80-99fb-11eb-9c10-fb3223c61bb7.png)

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: OnePlus 5

**Comment by mizzunet** [comment]
BTW, why need to show this 00:00 text above dialling while ringing the other end? This only be shown and started at time accepting the other end person, right?

**Comment by roeiedri** [comment]
Yeah youre right

**Comment by mizzunet** [comment]
> BTW, why need to show this 00:00 text above dialling while ringing the other end? This only be shown and started at time accepting the other end person, right?

This is still there
![Uploading Screenshot_20210518-232850_1.png…]()

**Comment by mizzunet** [comment]
> BTW, why need to show this 00:00 text above dialling while ringing the other end? This only be shown and started at time accepting the other end person, right?

![Screenshot_20210518-232850_1](https://user-images.githubusercontent.com/10193999/118701092-f8f9e600-b830-11eb-8c69-fabcb523f0ff.png)
ThisThis is still there

**Comment by roeiedri** [comment]
Oops lol
Ill remove it
