### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by gokulraam** [Chooloo/koler#186]
## Checklist

- [x] I am using the latest version - 1.0.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. You missed a call.
2. Open the app.
3. Missed call screen is opened.

### Actual behaviour

Missed call screen is opened after a call is missed.

### Expected behavior

App should open normally.

Related issue: #169 

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/40225391/114495567-d4956300-9c0d-11eb-8cfb-1c985bf86d71.mp4

### Device info
 - Android version/Custom ROM version: 9
 - Device model:

**Comment by roeiedri** [comment]
See #169
