### ISSUE TITLE
Missed call notification.

### ISSUE THREAD

**Issue by gokulraam** [Chooloo/koler#187]
### Checklist

- [x] I am using the latest version - 1.0.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Missed call notification should be handled by koler.

#### Is your feature request related to a problem? Please describe it

Clicking on missed call notification takes to the google dialer.

#### Additional context

Since this app is in development, didnt try with other dialer apps disabled so as not to be missed on any calls.

**Comment by DragonSerW** [comment]
Hello developer :-)
The problem is: missed calls are not displayed in red.
And it would be great if the will be dedicated tab of missed & no re-dialed calls.
Koler is great, but I wonder, if it is developed nowadays.
