### ISSUE TITLE
Cannot block the unwanted numbers

### ISSUE THREAD

**Issue by fossfann** [Chooloo/koler#193]
Hi,

We cannot block the phone numbers. We tried several ways but no luck.

Thanks in advance..

**Comment by roeiedri** [comment]
Can you be more specific?

**Comment by fossfann** [comment]
> Can you be more specific?

Sure. You know %95 dialer/phone apps have number blocking feature. You are being called by an ad company and you don't want to be called again by that number. Launched dialer app, go to recent calls and long tap on a number and select block this number. That's all.

**Comment by fossfann** [comment]
I found a duplicate thread

https://github.com/Chooloo/koler/issues/123

**Comment by roeiedri** [comment]
Ive added block contact and number buttons

**Comment by fossfann** [comment]
appreciated!
