### ISSUE TITLE
Cannot hang up phone call when locked the screen

### ISSUE THREAD

**Issue by fossfann** [Chooloo/koler#194]
Hı there,

I am making a phone call and locking the screen with power button for avoid accidental touches to any place. When i locked the screen with power button i cannot hang up the phone conversation. It stuck at call screen and there is no text or numbers on the call screen. Just call screen exist and yes/no buttons. That's all. This happened to me 14 times. Yes i counted.

Thanks in advance.

**Comment by EdricTruong** [comment]
Is there any reason you're not using the bug report template like everyone else which includes a compulsory checklist?

**Comment by roeiedri** [comment]
Hey, 
Are you using the latest version?
And can you by any chance send a video showing this bug?

**Comment by fossfann** [comment]
> Is there any reason you're not using the bug report template like everyone else which includes a compulsory checklist?

I couldn't achieve with that template sorry. I tried but no luck.

**Comment by fossfann** [comment]
> Hey,
> Are you using the latest version?
> And can you by any chance send a video showing this bug?

I can't because the privacy issues i can't blur the numbers. Sorry.

**Comment by EdricTruong** [comment]
> 
> 
> > Is there any reason you're not using the bug report template like everyone else which includes a compulsory checklist?
> 
> I couldn't achieve with that template sorry. I tried but no luck.

You mean you couldn't find it? I put it [here](https://pastebin.com/48XN8uxA) for you.

**Comment by fossfann** [comment]
will create with template
