### ISSUE TITLE
Cannot hangup phone call when locked the screen manually

### ISSUE THREAD

**Issue by fossfann** [Chooloo/koler#197]
## Checklist

- [x] I am using the latest version - 1.0.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Make a phone call
2. Talk some
3. Lock the screen (some mobile devices have failed sensors and they need lock the screen)
4. Unlock the screen
5. Try to hangup phone call

### Actual behaviour

When tried to hangup phone call after unlocked the screen Dialer app is freezing and cannot hangup the phone call. Stuck at calling screen and you need to force close from the Settings -> Apps -> Koler

### Expected behavior

When unlocked the screen we can hangup the call easily without any problem. When pressed the hangup (red button) button, phone call should be terminated immediately without freezing.

### Device info
 - Android version/Custom ROM version: Android 11, stock ROM, MIUI 12, not rooted
 - Device model: Mi Note 10 Lite

**Comment by roeiedri** [comment]
That's weird, I don't have that problem
What exactly do you see after unlocking the phone? the same screen as you had before locking the phone?

**Comment by fossfann** [comment]
> the same screen as you had before locking the phone?

No. Just call screen with Yes or No button. Both of them cannot be pressed because Dialer is frozen. I need to force stop the Dialer from Settings -> Apps.

**Comment by DigitalNXZ** [comment]
> > the same screen as you had before locking the phone?
> 
> No. Just call screen with Yes or No button. Both of them cannot be pressed because Dialer is frozen. I need to force stop the Dialer from Settings -> Apps.

Hi I don't know if you did those already: 
Try to deactivate Battery Usage for Koler "no restrictions"
Do you have gave it permissions to display on lock screen? may a bug it shows but it shouldn't?

I hope it helps, wish you good luck!

**Comment by fossfann** [comment]
> Try to deactivate Battery Usage for Koler "no restrictions

I did, not worked.

> Do you gave it permissions to display on lock screen?

I did, not worked.

> MIUI is really agressive on clearing and forcing to close if the apps has no permissions to run in some situations

Yes MIUI is really agressive but there is no problem with other dialer apps but they are not open source. For this reason i don't want to use them in my phone because all of them have lots of ads even if i disabled network access.

By the way thank you for your advises.
