### ISSUE TITLE
The old gesture UI was way better than the new improved one personally

### ISSUE THREAD

**Issue by karnotcycle** [Chooloo/koler#198]
I was a fan of the app "the older version" specifically which was heavily gesture driven and simple. After the major UI overhaul and the recent newer releases have turned it into a totally different app. I have been waiting to see where it goes, abstaining myself from writing this earlier. It will be great if the gestures are back, will they be back?

**Comment by roeiedri** [comment]
Can you elaborate whqt gestures you liked?

**Comment by karnotcycle** [comment]
Swiping right and left to pick up and hang up the call. It was really handy.
Right now I have to click on the green call button to pick up. I checked if we can enable it in the options but it seems like you have completely removed it from the revamped release.

**Comment by karnotcycle** [comment]
Thank you! Lots of love from this corner of the world!..
