### ISSUE TITLE
Speakerphone still doesn't work


### ISSUE THREAD

**Issue by mijorus** [Chooloo/koler#199]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'make a phone call'
2. Press on 'the button to activate the speaker'

### Logs

```

MODIFY_PHONE_STATE Permission Denial: setMode(MODE_IN_CALL) from pid=4576, uid=10189


getMode is call, Permission Denial: setSpeakerphoneOn from pid=4576, uid=10189
```

### Device info
 - Android version/Custom ROM version: Xiaomi MI5, havoc OS, Android 10

**Comment by fossfann** [comment]
Duplicate https://github.com/Chooloo/koler/issues/191

**Comment by roeiedri** [comment]
You helped me a lot with those logsss 
I basically give up on this issue for a while but apparently its an android version problem, so on lower android version the older solution will work but on newer ones I had to add a fix
Thanks
