### ISSUE TITLE
Disable on-call screen lock

### ISSUE THREAD

**Issue by lelibreauquotidien** [Chooloo/koler#202]
### Checklist

- [x] I am using the latest version - 1.0.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be interesting to have a setting to disable the use of the proximity sensor (which would disable the automatic turning off of the screen during the call)

#### Is your feature request related to a problem? Please describe it

On my phone (sony z3, lineage os 17.1), the proximity sensor is broken, so I can't make calls without the screen turning black and therefore, I lose all control over the phone

#### How will you/everyone benefit from this feature?

This feature could be useful for people who have a broken proximity sensor, or who just want to keep their phone screen on during a call

**Comment by fossfann** [comment]
If your phone's sensor is broken then you can lock the screen while you are talking with someone. This is the best solution for you.

**Comment by DigitalNXZ** [comment]
> If your phone's sensor is broken then you can lock the screen while you are talking with someone. This is the best solution for you.

Since I'm not a english native speaker I could understand it wrong but what I understood is his Phones screen is turning black in calls like it should be but he cannot disable it/ screen wake up so he cant not doing anything while he is in a call?

who knows but I dont think that your answer is the solution to it 

much love from me ^^
