### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by EdricTruong** [Chooloo/koler#203]
### Checklist

- [x] I am using the latest version - 1.0.6
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Format numbers entered into the dialer

Here's how my stock app does it:

![signal-2021-04-25-183230](https://user-images.githubusercontent.com/32976242/116017824-2c7d9200-a630-11eb-9ef4-5588e4b91dfe.png)

#### How will you/everyone benefit from this feature?

This will help users more easily read the number they are dialing.

**Comment by fossfann** [comment]
This is good but Koler should identify the country code because every country does have different area codes.
