### ISSUE TITLE
constant nagging about making default dialer

### ISSUE THREAD

**Issue by brainchild0** [Chooloo/koler#204]
# Problem

Koler nags constantly about setting itself to the default dialer application. Asking once upon startup is helpful, but no more.

In contrast to the current behavior, the application should ask only once per session. It also should  provide an option to disable the requests, such as through a "Never ask again" response button, and with an option on the application settings.

# Environment
- **Application version:** 1.0.6
- **Android release:** Pie/9
- **Android customization:** Havoc-OS, Magisk
- **Hardware:** Pixel 3

**Comment by roeiedri** [comment]
You can check an option on the dialog saying "Do not ask again", it's using the phone's default dialog so I don't have much to do about it.

**Comment by brainchild0** [comment]
Are you saying the dialog box is generated by the system not the application?

In my environment there is no checkbox.

---


![Screenshot_20210517-082804](https://user-images.githubusercontent.com/34869175/118503708-debcec80-b6f8-11eb-9c72-36ef6099a14b.jpg)

**Comment by roeiedri** [comment]
Yes its made by the system

**Comment by brainchild0** [comment]
Does the application control when the box gets displayed?
