### ISSUE TITLE
Group the number of calls that are made to same number to avoid clutter

### ISSUE THREAD

**Issue by pixincreate** [Chooloo/koler#207]
### Checklist
- [x] I am using the latest version - v1.0.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Group the number of calls made to a phone number.  
**For example:** I called to this number *1234567890* 3 times. It now shows like this:  
- *1234567890*
- *1234567890*
- *1234567890*  
What would be optimal is this:  
- *1234567890* (3).  
When you click on it, It opens this:  
- *1234567890* with time of call.
- *1234567890* with time of call.
- *1234567890* with time of call.

#### Is your feature request related to a problem? Please describe it
Kinda, yes but no. I wanted to get rid of clutter. Grouping them would be optimal.

#### Additional context  
Unedited screenshot. 
![Screenshot_20210429-204629](https://user-images.githubusercontent.com/69745008/116575151-0277e880-a92c-11eb-9950-7099c7ec8bb6.png)  
Doesn't this look ugly and cluttered and messed up?  
Doesn't the below one look cleaner.? You've to click on History to view the jumber of times you've called.    
![Screenshot_20210429-204830_1](https://user-images.githubusercontent.com/69745008/116575495-51be1900-a92c-11eb-9b64-71950c5cc8d4.png)  

#### How will you/everyone benefit from this feature?
Makes the Recents UI look cleaner and hence less confusion and clutters.

**Comment by InterstellarPotato20** [comment]
I hope this is kept it optional. I prefer the current style.

**Comment by mikenrafter** [comment]
This feature is present, and this issue should now be closed.
