### ISSUE TITLE
App force quits when scrolling through recents fast

### ISSUE THREAD

**Issue by The-Linux-User** [Chooloo/koler#208]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to 'Recents'
2. Scroll down really fast

### Actual behaviour
The app force quits

### Expected behavior
It stays open

### Device info
 - Android version/Custom ROM version: Android 11 OxygenOS
 - Device model: OnePlus 8

**Comment by The-Linux-User** [comment]
I have just noticed that you don't have to scroll fast, it also crashes when you slowly scroll down for a while but it crashes much faster when scrolling fast even when just scrolling up and down the first few entries.

**Comment by roeiedri** [comment]
Ill need to see some logs because that has never happened to me with the latest version
Maybe I fixed that since the latest github release because I had some bugs with opening contacts but I'm not sure it's related.
Anyway today I'm uploading a new release so it might be better idk :)

**Comment by DigitalNXZ** [comment]
@The-Linux-User I have the same problem.. I think a Hidden number crashed koler, if you delete call history it works, after a call still works and after call with hidden number = broke
