### ISSUE TITLE
Hang Up button not working

### ISSUE THREAD

**Issue by fourteen-1** [Chooloo/koler#213]
Pressing the hang up button isn't working

**Comment by fourteen-1** [comment]
> I know it for first time,
> But u should swipe left hang up button to work. :) And hang up call...

Interesting mechanism. I can see good reasons for making the button work like that, like prevent accidental hang ups. 

But maybe implement an option to switch to just press button to hang up? Or at least make it obvious that you are required to swipe left.

**Comment by roeiedri** [comment]
Yeah the problem was that swiping the button would override the clicking which prevented the user from being able to click the button and only swiping it would trigger it.

**Comment by roeiedri** [comment]
For now I'm removing swiping, it disables the click animation plus it show any swipe animation.
Adding those animation is a bit more work and isn't the most important right now :(
But feel free to add an enhancement issue for swiping triggers.
