### ISSUE TITLE
while Calling screen shows receiving recieving call

### ISSUE THREAD

**Issue by Gottarocket** [Chooloo/koler#216]
Today when I use koler to call I got a screen showing the screen when you recieve a call that is with call receive or decline buttons instead of call screen with speaker dialling numbers and ol Please do check if its a bug as it worked fine after I closed and tried it again

**Comment by roeiedri** [comment]
When does this happen? Also do you have the latest version?

**Comment by Gottarocket** [comment]
Its random and yes I have the latest release

**Comment by roeiedri** [comment]
Fixed in latest commit
