### ISSUE TITLE
Add to GooglePlay

### ISSUE THREAD

**Issue by ueen** [Chooloo/koler#218]
This app looks really cool and promising, simple yet elegant, would you consider uploading it to Google Play? You could offer it there for a small fee, like 1-2€ I would definitely get it :)

I had a Samsung recently and really liked the colorful gradient blured background during a call, maybe you could do something similar? 

Reference https://www.sammyfans.com/wp-content/uploads/2020/11/sammy-fans-samsung-one-ui-3-call-background-1.jpg

**Comment by roeiedri** [comment]
I've created a release, a problem occurred regarding the pay configurations and all that stuff.
I've contacted google, hope to get a response soon :)
