### ISSUE TITLE
Dial Scroll

### ISSUE THREAD

**Issue by ueen** [Chooloo/koler#220]
If there are suggestions in the dialer, the whole view scrolls weirdly to this position

**Comment by roeiedri** [comment]
Can you elaborate whats the problem?
You want the scroll indicator removed?

**Comment by ueen** [comment]
Just checked, not appearing on pixel, only Samsung A40 (maybe screensize related?)


https://user-images.githubusercontent.com/5067479/118605571-ba274a00-b7b6-11eb-8ec9-42a341fdffcb.mp4

**Comment by ueen** [comment]
Just checked, not appearing on pixel, only Samsung A40 (maybe screensize related?)


https://user-images.githubusercontent.com/5067479/118606183-679a5d80-b7b7-11eb-996a-12401479919c.mp4


(I'm just typing numbers and when the contact suggestions appear, the whole DialerView jumps/scrolls down and cuts off the buttons at the bottom, of I scroll back up, it doesn't jump anymore)

**Comment by mizzunet** [comment]
Same happens here too

**Comment by mizzunet** [comment]
https://user-images.githubusercontent.com/10193999/118697654-28a6ef00-b82d-11eb-995c-af1d961ef6b1.mp4

Same here.
