### ISSUE TITLE
Option to hide call logs from a specific number

### ISSUE THREAD

**Issue by dvlpr-shivendra** [Chooloo/koler#221]
### Checklist

- [x] I am using the latest version - 1.09.
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want 
Can we have option to hide call logs of a specific number. I tried multiple dialer apps but could not find this option.

**Comment by roeiedri** [comment]
Can you be more specific?
You mean that call logs wont be visible from the recents list?

**Comment by dvlpr-shivendra** [comment]
Yes if we can have option to hide all call logs of a specific number.
