### ISSUE TITLE
Search icon glitch

### ISSUE THREAD

**Issue by mizzunet** [Chooloo/koler#222]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Perform swipe down gesture function

### Actual behaviour

The search icon of Search field disappears and re-reappeares once touc the screen again

### Expected behavior

This shouldn't happen. Also a suggestion is that, there's no need for this refresh function for dialer app, right?

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/10193999/118697339-d06fed00-b82c-11eb-97ec-c0c59d35837a.mp4

### Device info
 - Android version/Custom ROM version: Android 11
 - Device model: OnePlus 5

**Comment by roeiedri** [comment]
Yeah you are probably right ill remove the icon visibilty change.
Did that just to make it look better so you know the focus is on the search bar.
About thr refresh, someone requested drag down to search feature i just didnt change the icon of the refresh circle so yeah :)

**Comment by mizzunet** [comment]
> Yeah you are probably right ill remove the icon visibilty change.
> Did that just to make it look better so you know the focus is on the search bar.
> About thr refresh, someone requested drag down to search feature i just didnt change the icon of the refresh circle so yeah :)

Great 👍. However, why would one need that drag down refresh

**Comment by roeiedri** [comment]
To have some way to trigger the search bar from the bottom of the screen

**Comment by mizzunet** [comment]
> To have some way to trigger the search bar from the bottom of the screen

I had a thought on it. 
Presently both tab(Contacts, Recent) have a different search bar, right? So, wouldn't it be nice that both have a single common search bar? Like when we type something there, searching happens on both Contacts and Recenet tab together?

**Comment by roeiedri** [comment]
The first version had that
But code and design wise, having a search bar for every list view has its
benefits.
