### ISSUE TITLE
Call with sim1 or sim2 ?

### ISSUE THREAD

**Issue by Mojienjoynent** [Chooloo/koler#227]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Please add this feature that call with sim1 or sim 2 !
When we want to call with sim card 1, we should go to phone settings and set all calls to sim 1 (picture 1). 
If I set this to " ask every time" , I can't call at all and stuck at "call in progress" (picture 2) And No call!.

You can create two "green call button" for each sim card. 
Or 
when we tap on "green call button" , a show up (dialog pop up) appears and we choose sim 1 or sim2!! 

#### Additional context

Picture 1 👇🏽
![Screenshot_20210519-214346](https://user-images.githubusercontent.com/68327458/118856502-44bd9580-b8ec-11eb-80c5-f327fec37149.png)
Picture 2 👇🏽
![Screenshot_20210519-215105](https://user-images.githubusercontent.com/68327458/118857069-e0e79c80-b8ec-11eb-8727-ad3388b2d48e.png)

#### How will you/everyone benefit from this feature?

After this feature , we can decide that call with sim1 or sim2 at any time... :)

**Comment by DigitalNXZ** [comment]
is this not already in the app? I dont use a 2nd sim so I cNt say anything about what you want..
![Screenshot_2021-05-20-00-37-49-522_com chooloo www koler](https://user-images.githubusercontent.com/53005759/118894031-ca165b00-b896-11eb-9ffe-64082ba71511.jpg)
-> sim selection?

**Comment by roeiedri** [comment]
@DigitalNXZ its disabled because its not done yet :)
Ill put this feature higher on my priority list.

**Comment by Mojienjoynent** [comment]
> @DigitalNXZ its disabled because its not done yet :)
> Ill put this feature higher on my priority list.

Ok!

**Comment by roeiedri** [comment]
@Mojienjoynent Hey could you be my tester for this? I dont have 2 sims and emulators don't supprt 2 sims so i need a real phone :)

**Comment by LeOS-GSI** [comment]
If you need a tester, in my group we have some people with 2 active SIM devices. we can test for you

**Comment by Mojienjoynent** [comment]
> @Mojienjoynent Hey could you be my tester for this? I dont have 2 sims and emulators don't supprt 2 sims so i need a real phone :)

Yeah, please, I want to test it, please send it for me bro. :)
How I get it?

**Comment by roeiedri** [comment]
@Mojienjoynent 
I have a working and tested version locally, need to do some adaptations to master but will merge it soon.

**Comment by sparevermicelli** [comment]
Hello, has it been already merged? 
I am currently testing with v1.2.0, but it's not working correctly.

(I've commented it here: https://github.com/Chooloo/koler/issues/19#issuecomment-969177160 )
