### ISSUE TITLE
Unofficial telegram group

### ISSUE THREAD

**Issue by jakubfabijan** [Chooloo/koler#228]
I made with my friend a telegram group so we can talk about the Koler project. You can join it [here](https://t.me/joinchat/_S5OJUMTur40N2U0)

**Comment by shuvashish76** [comment]
Hello @jakubfabijan you are inactive on Telegram group.
It is possible to create another team but at this point creating another official group by Mr Roei Edri himself seems unnecessary.
Can you please transfer the ownership to the main app creator Mr @roeiedri & make this group official?

Please check Telegram group messages I've some other suggestions as well.

Thankyou🙏🏿

**Comment by shuvashish76** [comment]
GitHub Bot test message
