### ISSUE TITLE
Last contact cuts off + other issues/suggestions

### ISSUE THREAD

**Issue by Kokofruits1** [Chooloo/koler#229]
### Device info
I am using a Redmi note 5 pro which has an 18:9 display. I am running de Googled Havoc OS 4.1 (based on Android 11).
### Description of the main issue
I recently updated to the newest version (1.0.9) and it started to cut off the last contact. I tried compact and normal, compact cuts it off more. Latest version that doesn't cut off is 1.0.4. 
### Other issues
Editing a contact requires another app (would be nice to be integrated with the app).
When deleting call history I need to go out of the app and go into it again for it to show as deleted (not a huge issue).
Call history scroll indicator looks too big, maybe a format like DD.MM.YY. would look better. Also the text in the circle looks a bit too big.
### More feedback
I think that this app has a huge potential. It already looks awesome but it needs some polishing. Hope you develop an SMS app in the future since you have great design skills.

**Comment by r8tr0** [comment]
Hi i am also facing this issue where the last contact is cutoff regardless of which mode I happen to be in. I am  currently using a realme 6 (with standard realms ui ).
Screen size 6.5 inches, total screen area 102.0 cm2, with a resolution of 1080 x 2400 pixels.

**Comment by osjasmine** [comment]
Facing same issue here too. The last contact is cut off.

**Comment by fahimscirex** [comment]
Hello, I'm facing the same issue. Even in the latest release. I've a J2XLTE with ViperOS 7.1.2.

**Comment by osjasmine** [comment]
Issue fixed for me in the latest release v1.3.0. Thank you dev.
