### ISSUE TITLE
Android special codes

### ISSUE THREAD

**Issue by 4PERTURE** [Chooloo/koler#236]
## Checklist

- [x] I am using the latest version v1.0.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to the dialer
2. Dial in a special code like *#*#4636#*#*

### Actual behaviour

Nothing

### Expected behavior

Open testing menu in settings

### Device info
 - Android version/Custom ROM version: 11/DotOS 5.1.1
 - Device model: Redmi Note 9S

**Comment by roeiedri** [comment]
Should work, reopen if still happens

**Comment by 4PERTURE** [comment]
damn, that was a long time ago. unfortunately i don't use android anymore, so i can't try it again!! > Should work, reopen if still happens
