### ISSUE TITLE
Show Koler keypad only

### ISSUE THREAD

**Issue by shuvashish76** [Chooloo/koler#243]
- [x] I am using the latest version - 1.0.9 (F-droid version)
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Is your feature request related to a problem? Please describe it
When I click on the keypad button it pops up my device keypad too. But that's not the case in the system default phone app.

Koler Keypad
![image](https://user-images.githubusercontent.com/48226312/129886810-10e04921-93c4-41b1-a717-39fd17dfa627.png)

Device default phone app
![image](https://user-images.githubusercontent.com/48226312/129886870-cc7aaa78-29ef-40fa-b8aa-34f5ff42cd8a.png)

#### Expected Behaviour

Show only Kooler Keypad not system/installed keypad

#### Additional context
Device Details:
Model: Lenovo Tab4 8 Plus (TB-8704X)
Android version: 8.1.0
Used keyboard: [AnySoftKeyboard](https://f-droid.org/packages/com.menny.android.anysoftkeyboard)

**Comment by roeiedri** [comment]
Please use latest version a check if that still happens

**Comment by shuvashish76** [comment]
Yes checked test release v1.0.9 (from telegram group). Fixed. Thanks
Closing...
