### ISSUE TITLE
Option for turn on/off loudspeaker and mute in notification tile

### ISSUE THREAD

**Issue by karthiceaswar** [Chooloo/koler#250]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Option for turn on/off loudspeaker and mute in notification tile. Since we now only has the hungup option in notification tile, it would be great to have  loudspeaker and mute in the tile

#### How will you/everyone benefit from this feature?

This feature will help us colonize the galaxy!

**Comment by roeiedri** [comment]
Added in commit c3c954d01c2ce003b2b17141ff3e1b534d7bcb39
