### ISSUE TITLE
Group call history of same number under a single list till it breaks by another number

### ISSUE THREAD

**Issue by karthiceaswar** [Chooloo/koler#251]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Group call history of same number under a single list till it breaks by another number. (I have had like 5 missed call from my better half and it all shows as a separate 5 call list. I would be great if we could group them. we can do either all related a number in single list like all received, dialed, missed or each these categories as a list. 

#### How will you/everyone benefit from this feature?

This feature will help us colonize the galaxy!

**Comment by LeOS-GSI** [comment]
I don't like this feature request, because if it is grouped, I can't see the caller time. I want see for every call a single line with date and time of call.

**Comment by roeiedri** [comment]
Sorry, currently won't add this feature as it's complicating the app a bit.
The way it is right now is more simple and straight forward.
Might get back to it in the future though :)
