### ISSUE TITLE
When keyboard is up for searching. pressing back close the app itself instead of slide down the keyboard.

### ISSUE THREAD

**Issue by mahmoudk1000** [Chooloo/koler#258]
## Checklist

- [x] I am using the latest version - 1.0.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open koler
2. Press on search bar
3. Press back

### Actual behaviour

The app itself close

### Expected behavior

The keyboard should close or slide down

### Screenshots/Screen recordings

[Here you go](https://imgur.com/a/gpfaZgn)

### Logs

Doest really require a one

### Device info
 - Android version/Custom ROM version: Custom ROM / Lineage 18.1 Android 11
 - Device model: Poco X3 Pro

**Comment by roeiedri** [comment]
It's because the swipe to go back touches the screen before it goes back.
The touch outside of the keyboard closes it and then you go back (the swipe).
If you'll switch your os to navigation button instead of "swipe to go back" you'll see it works.
