### ISSUE TITLE
Favorite section not visible

### ISSUE THREAD

**Issue by mahmoudk1000** [Chooloo/koler#264]
## Checklist

- [x] I am using the latest version - 1.0.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open app

### Actual behaviour

Not visible

### Expected behavior

To be visible / seen

### Device info
 - Android version/Custom ROM version: lineage 18.1
 - Device model: poco x3 pro

**Comment by shuvashish76** [comment]
@mahmoudk1000 Same here. I don't think it's device specific.
I guess it is test release v1.0.9 (from telegram group).

**Comment by roeiedri** [comment]
4023cfa0ec45e4b63fa5133f76d6b3ffed52e5ad
