### ISSUE TITLE
Autofill phone number field when a phone number is shared to the app

### ISSUE THREAD

**Issue by realmain** [Chooloo/koler#270]
### Checklist

- [x] I am using the latest version - 1.0.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Autofill phone number field when clicking on a phone number in another app that automatically launches Koler.

#### Is your feature request related to a problem? Please describe it

When you click on a phone number on Google Maps, Yelp, Signal, etc, it automatically opens up the Koler app, but it does not fill the phone number field to be able to call out.

#### How will you/everyone benefit from this feature?

It is convenient to click on a phone number in another app, have it autofill in Koler, to make a call.

**Comment by roeiedri** [comment]
Fixed in latest release
