### ISSUE TITLE
Target Android 12

### ISSUE THREAD

**Issue by TriStaRvOiD** [Chooloo/koler#275]
Koler currently seems to target Android 11.
Also, Material You support could make the app look better.

**Comment by LeOS-GSI** [comment]
> Koler currently seems to target Android 11. Material You support could also make the app look better.

I don't think so. I don't what all people do like on this 'Material' design. And Koler is working fine on Android 12. No need for changes

**Comment by TriStaRvOiD** [comment]
Targets android 12 now
