### ISSUE TITLE
apk missing for v1.1.2

### ISSUE THREAD

**Issue by zer0fl0w** [Chooloo/koler#278]
please add the apk-file for v1.1.2 under releases.

thanks.

**Comment by roeiedri** [comment]
Is that necessary? Its not the latest version

**Comment by shuvashish76** [comment]
Now it doesn't matter. Please close this issue. @roeiedri 

Suggestions
- Rename apk files with version code, before uploading files to release section. It will help users to recognize app version if someone downloaded multiple apk files from GitHub.
- add Full Changelog: [v1.3.4...v1.3.6](https://github.com/Chooloo/koler/compare/v1.3.4...v1.3.6). It looks more professional IG & useful to check changelog with previous version.
- Change headlines with Koler version name & subheading with "What's Changed".

For reference do check k9mail [releases](https://github.com/k9mail/k-9/releases)...

**Comment by roeiedri** [comment]
Thanks for the suggestions @shuvashish76
