### ISSUE TITLE
Merge duplicates

### ISSUE THREAD

**Issue by Gottarocket** [Chooloo/koler#285]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Many duplicate contacts from phone and sim needs to be merged or atleast should be visible once 

#### Is your feature request related to a problem? Please describe it

It confuses when you have two names and if the number is different its fine but when everything is similar but because one is on sim and another on mobile or online account shouldnt show multiple instances of it

#### How will you/everyone benefit from this feature?
Will avoid clutter
Scrolling deep down just because you have many duplicates can be avoided

**Comment by roeiedri** [comment]
Does this still happen in latest version?

**Comment by mikenrafter** [comment]
Duplicates are merged in the latest version. But if there's multiple numbers for a single contact with a(n) instance(s) for each, then both numbers should be displayed below the contact, and duplicates should only be combined when they have the same number.

**Comment by roeiedri** [comment]
> Duplicates are merged in the latest version. But if there's multiple numbers for a single contact with a(n) instance(s) for each, then both numbers should be displayed below the contact, and duplicates should only be combined when they have the same number.

In the latest version, you can see all numbers accounts under a certain contact
