### ISSUE TITLE
Crash upon call has ended

### ISSUE THREAD

**Issue by Paritosh-Tripathi-Github** [Chooloo/koler#287]
## Checklist
- [x] I am using the latest version - 1.2.0
 - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Call anyone
2. Press on 'end button'
3. The app will crash (Koler has stopped working)

### Actual behaviour
The app crashed (Koler has stopped working)

### Expected behavior
It should not have crashed and should have returned to recents screen.

### Device info
 - Android version: 9

**Comment by roeiedri** [comment]
If you have any way too show a traceback that would be extremely helpful since i couldn't reproduce the crash with emulators.
