### ISSUE TITLE
Last item of contacts/recents list not visible.

### ISSUE THREAD

**Issue by Paritosh-Tripathi-Github** [Chooloo/koler#289]
## Checklist
- [x] I am using the latest version - 1.2.0
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Press on Contacts/Recents
2. Go to the end of the list.
3. The last contact is not visible at all.

### Fix
It can easily be fixed by adding padding bottom or margin bottom to the list.

### Actual behaviour
The last item didn't show properly.

### Expected behavior
The last item should have shown properly and there should have been some space at the bottom.

### Device info
 - Android version: 9

**Comment by Ilithy** [comment]
I have the same behavior on my two smartphones (Android 11 and 12 - Koler v1.3.6 - installed from F-droid)
