### ISSUE TITLE
2x SIM calling doesn't work

### ISSUE THREAD

**Issue by sparevermicelli** [Chooloo/koler#290]
Hi,
this bug is not yet solved.

When no SIM is selected in the contact as default, then even though the Koler is asking for SIM - no call is placed (no ring tone, always "dialing")
When I select for example SIM1 as default for one contact, then in Koler I am asked again to choose SIM (Here I'd also argue that it's not a correct behavior, or?). When I now choose SIM2, the call is still placed under default SIM1.

_Originally posted by @sparevermicelli in https://github.com/Chooloo/koler/issues/19#issuecomment-969177160_

**Comment by sparevermicelli** [comment]
also referencing #227

**Comment by roeiedri** [comment]
Fixed in latest release
