### ISSUE TITLE
Keywords output not right

### ISSUE THREAD

**Issue by dhishkyaon** [Chooloo/koler#297]
## Checklist

- [x] I am using the latest version - 1.3.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Just search for contacts
Working fine with FlorisBoard but not working right with Default OS Keyboard and OpenBoard.

### Actual behaviour

Keywords output is not right. keywords are repeating

### Expected behavior

Keywords output not right. 

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/88529066/147718566-6bfacc06-0fc4-4ffc-8ed3-734d43b25baf.mp4

### Logs

Not available

### Device info
 - Android version/Custom ROM version: 12
 - Device model: Pixel 4a

**Comment by regaldude** [comment]
Why was this closed?
