### ISSUE TITLE
Search contacts field duplicates characters

### ISSUE THREAD

**Issue by stavrosl7** [Chooloo/koler#302]
In the search contacts field:
While  pressing any key on the keyboard, it copy-pastes the whole field every 2 keystrokes:

E.G. writing ABC
Field values: a->aab>aabc>aabcaabcd

Tested with openboard.

**Comment by gun4qmm7h** [comment]
I tested it out with openboard and same bug happen.
Works normal with florisboard though

**Comment by osjasmine** [comment]
With openboard when I turn off "Show correction suggestions" this issue disappears. For some reason, the main suggestion is automatically pasted into the search field.
