### ISSUE TITLE
Unpleasant jump of dialer keyboard

### ISSUE THREAD

**Issue by FreeCap23** [Chooloo/koler#303]
In the digit keyboard screen, when you start typing numbers the card containing the keyboard jumps up and leads to the keyboard being in a slightly different place. 
This makes it hard to type numbers when you're not expecting the jump.

https://user-images.githubusercontent.com/62378314/148034355-9961747b-5b39-4e3f-ba8b-b1b1e06331b5.mp4

Koler version: 1.3.2
Device: Samsung Galaxy A52 5G 
Android version: 11
Stock ROM

**Comment by roeiedri** [comment]
What's your screen size?

**Comment by FreeCap23** [comment]
> What's your screen size?

From gsmarena.com:
6.5"
1080x2400
