### ISSUE TITLE
I love this app

### ISSUE THREAD

**Issue by gun4qmm7h** [Chooloo/koler#304]
Just wanted to say that I recently change koler to the default app and I love the look/feel of it. Keeps up the amazing work. Can't wait to see how this app will look in the future .

**Comment by roeiedri** [comment]
Thank you very much! Please consider supporting us using the donate button in the readme page so we can continue to work on this app :)

**Comment by gun4qmm7h** [comment]
I'm broke. Any other way to help?

**Comment by roeiedri** [comment]
Lol same.
No bro, appreciate the compliments though.
