### ISSUE TITLE
Can't block numbers

### ISSUE THREAD

**Issue by yephny** [Chooloo/koler#310]
- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

There was an option to block numbers, but it seems to be gone.

**Comment by roukouna** [comment]
this function must return cannot a dialer not have Call blocker . today (year 2022) .if it does not have it is not serious program

**Comment by roukouna** [comment]
> this function must return cannot a dialer not have Call blocker . today (year 2022) .if it does not have it is not serious program

the feature disappeared in version 1.3.2 ....1.3.3

**Comment by Ilithy** [comment]
Personally, I use the Silence application as a call blocker (it is very good in this field, more practical than the callblocker of the dialers I tested), so I don't care (for example, the dialers of aosp doesn't have a callblocker), on the other hand, Koler is really beautiful, very purified, I start to use it only, but if it works well, it will be adopted on my pixel 6 pro under grapheneos. Thanks a lot to the developer <3

**Comment by yephny** [comment]
@Ilithy It's much easier to block a number within the app than launching another app / sharing the number with it.

**Comment by Ilithy** [comment]
@yephny That's the difference with Silence, it doesn't work on a whitelist/blacklist basis, it blocks everything except exceptions (contacts, already contacted etc...), so I don't have to worry about it, it's infinitely more convenient. Besides I prefer to have two applications that do their respective jobs very well, than one, that does nothing well 😉

**Comment by yephny** [comment]
Then you have no reason to hinder a feature request.

**Comment by Ilithy** [comment]
> Then you have no reason to hinder a feature request.

I'm sorry you think this, I don't want to prevent this feature, I just want to give my opinion on it.
