### ISSUE TITLE
Copying a number in Recents

### ISSUE THREAD

**Issue by yephny** [Chooloo/koler#328]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Being able to copy numbers easily. In both tabs, you should be able to hold down on a phone number to copy it to the clipboard.

#### Is your feature request related to a problem? Please describe it

Imagine someone not in your contacts calls you, which puts their number in Recents. You want to copy the number because you want to send it to someone, look it up in an online database, or paste it into a blocking app. You have to manually type out the whole number with Koler.

#### How will you/everyone benefit from this feature?

Being able to copy would surely benefit a lot of users per examples given above.

**Comment by roeiedri** [comment]
You can already copy a number by long clicking under a contact.
Though in recents you can't so ill leave the issue opened.
