### ISSUE TITLE
Missing strings and possible errors

### ISSUE THREAD

**Issue by strel** [Chooloo/koler#329]
## Checklist

- [x] I am using the latest version - 1.4.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Description
I've noticed some strings apparently not being translated and not present in strings.xml file for translation:
"Should ask for sim" setting in the settings dialog
"Should block number option" setting in the settings dialog
"Pick a color" in the Accent Color setting dialog
"Yesterday" in the Recents page

Also possibly some errors in strings.xml:

```
<string name="error_no_permissions_edit_call_log">No permission to change call log :)</string>
```
probably should say "No permission to change call log :("

These strings are identical:
```
<string name="error_no_permissions_phones">I need permission to read contacts :)</string>
<string name="error_no_permissions_contacts">I need permission to read contacts :)</string>
```
but 1st one seems wrong, probably should say "I need permission to make calls :)"

And finally, strings in sections 
```
<!--region pref key-->
```
as preferences keys they are
```
<!--region dialpad letters-->
```
as standard dialpad keys (I understand them to be), does not seem to be strings to translate, a note about that would be helpful.

**Comment by roeiedri** [comment]
Will improve with contributers adding strings
