### ISSUE TITLE
Copying a number in Contacts crashes the app

### ISSUE THREAD

**Issue by yephny** [Chooloo/koler#340]
## Checklist

- [x] I am using the latest version - 1.4.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to a contact.
2. Tap on their name.
3. Hold down on the number.
1. The number will be copied but the app will crash.

### Actual behavior

The number is copied but the app crashes.

### Expected behavior

The app should not crash.

### Logs

http://0x0.st/oK_G.txt

### Device info
Android version/Custom ROM version: LineageOS 10

**Comment by roeiedri** [comment]
I can't reproduce that bug, it doesn't happen when I copy the number.
Can you send the rest of the traceback?

**Comment by Ilithy** [comment]
same, no crash when copying number, contact list or recent numbers.

Pixel 6 Pro
Grapheneos - Android 12
Install: Github
Version: 1.4.1
select as default dialers: Yes

**Comment by yephny** [comment]
@roeiedri I am using [Scoop](https://www.f-droid.org/packages/taco.scoop/) to get the crashlog, and what I posted is all there's to it.

**Comment by yephny** [comment]
Updated to 1.4.1 and [this is the new crashlog](http://0x0.st/oPLu.txt).

**Comment by yephny** [comment]
Reinstalling the app (from F-Droid, this time) solved the issue.
