### ISSUE TITLE
Status bar is almost invisible in white mode  and unable to switch theme.

### ISSUE THREAD

**Issue by OkMohit** [Chooloo/koler#362]
## Checklist

- [x] I am using the latest version - 1.4.3 
- [] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

Changing themes mode, actually doesn't do anything. tried several times to switch theme but button almost unresponsive.

Also when app is in white mode (hadn't tested in dark mode) , status bar is almost white, making status icons almost invisible.

### Expected behavior

Expected to switch theme 

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/93777145/158130784-ca7c2a45-18ff-42b4-b39f-20b6b8e8e087.mp4

### Device info
 - Android version/Custom ROM version: Stock Color OS / Realme UI 1.0 Android 10
 - Device model: RMX2185

**Comment by elesto** [comment]
Same issue  but with the dark theme the status bar is full white and i can't see anything

Android 12

**Comment by xdubx** [comment]
> Same issue but with the dark theme the status bar is full white and i can't see anything
> 
> Android 12

I have the same issue.

**Comment by roeiedri** [comment]
Fixed
