### ISSUE TITLE
Koler doesn't show the call time when receiving a call

### ISSUE THREAD

**Issue by DodoLeDev** [Chooloo/koler#367]
## Checklist

- [x] I am using the latest version - 1.4.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Call someone with Koler
2. You see the call time at the top of the screen
(2 bis. Hang up the call)
3. Now call the phone which have Koler installed with another phone
4. When you answer the call, you will not see the call time as you could expect

### Actual behaviour
The call time isn't shown when receiving a call

![](https://i.imgur.com/Sll47lT.jpg)

### Expected behavior
The call time should be visible, as you can see when calling someone

![](https://i.imgur.com/2KNVBCi.jpg)

### Logs
Not needed

### Device info
 - Android version: Android 11 - MIUI 12.5
 - Device model: Xiaomi Redmi Note 9

**Comment by DodoLeDev** [comment]
Would it be possible to add the `bug` label to this issue?

**Comment by roeiedri** [comment]
Should be fixed now, will be in next release
