### ISSUE TITLE
Buttons are excessively big!

### ISSUE THREAD

**Issue by DodoLeDev** [Chooloo/koler#371]
## Checklist

- [x] I am using the latest version - 1.4.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour
Buttons are too big!
Particularly in the Calling screen!

**Here are some screenshots:**
| Calling screen | Home screen |
| --- | --- |
| [<img src="https://user-images.githubusercontent.com/59477313/159167220-6a21fa2d-593f-4c84-9a36-840dfd95f5f6.jpg" width="480"/>](https://user-images.githubusercontent.com/59477313/159167220-6a21fa2d-593f-4c84-9a36-840dfd95f5f6.jpg) | [<img src="https://user-images.githubusercontent.com/59477313/159167244-da4b1490-7e91-4432-8870-8fb395ecc686.jpg" width="480"/>](https://user-images.githubusercontent.com/59477313/159167244-da4b1490-7e91-4432-8870-8fb395ecc686.jpg) |

### Expected behavior
Could it be possible to restore buttons size of the last version?

**Here is a little comparison:**
| Size of the dial pad button in 1.4.2 | And in 1.4.3 |
| :---: | :---: |
| [<img src="https://user-images.githubusercontent.com/59477313/159167325-2f37ec87-1574-49e4-8fcc-2ab6ef3a23a0.png" width="480"/>](https://user-images.githubusercontent.com/59477313/159167325-2f37ec87-1574-49e4-8fcc-2ab6ef3a23a0.png) | [<img src="https://user-images.githubusercontent.com/59477313/159167244-da4b1490-7e91-4432-8870-8fb395ecc686.jpg" width="480"/>](https://user-images.githubusercontent.com/59477313/159167244-da4b1490-7e91-4432-8870-8fb395ecc686.jpg) |
| Ideal button size 👆 | Current button size 👆 |

As you can see, the button is bigger!

### Screenshots/Screen recordings
See above 👆 

### Logs
Not needed

### Device info
 - Android version/Custom ROM version: Android 11 - MIUI 12.5
 - Device model: Xiaomi Redmi Note 9

**Comment by sonalder-darlene** [comment]
I agree that smaller (not by much) buttons would be more pleasant to use !

**Comment by bagajohny** [comment]
I dont mind the current size of buttons. So if possible you should get an option to choose the button size in settings.

**Comment by nafarinha** [comment]
Sorry for the original post author if this is duplicate, but I can't visualize the screenshots.

I have a similar issue with version v.1.4.3. I'm my case I have a device with an uncommon screen size and resolution: 3.1-inch squared screen with 716*720 resolution:
![img1](https://user-images.githubusercontent.com/1145780/161566704-372c8d74-c8e2-4ba3-9940-c0f377369e46.png)

As shown on the screen shot, it is almost impossible to see the numbers dialled on the top of the screen. If there was an option to resize the buttons it would be very helpful.
