### ISSUE TITLE
Background screen not well dimmed

### ISSUE THREAD

**Issue by DodoLeDev** [Chooloo/koler#373]
## Checklist

- [x] I am using the latest version - 1.4.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour
The background screen is insufficiently dimmed!

### Expected behavior
Background screen should be darker!

### Screenshots/Screen recordings
| Call log in foreground | Dial pad opened - Call log in background | Settings opened - Call log in background |
| --- | --- | --- |
| ![Screenshot_2022-03-20-17-06-10-186_com chooloo www koler](https://user-images.githubusercontent.com/59477313/159174045-320dd7ce-6c32-41d4-864b-9a25c32668b2.jpg) | ![](https://user-images.githubusercontent.com/59477313/159174028-6b7d9154-b452-4845-a2e5-bb63726ad9ca.png) | ![Screenshot_2022-03-20-17-06-16-259_com chooloo www koler](https://user-images.githubusercontent.com/59477313/159174034-f27e9793-405e-4e51-873d-91a155f317ab.jpg) |

### Logs
Not needed

### Device info
 - Android version: Android 11 - MIUI 12.5
 - Device model: Xiaomi Redmi Note 9

**Comment by roeiedri** [comment]
Not a bug, just a personal opinion
