### ISSUE TITLE
Material you

### ISSUE THREAD

**Issue by ansarimohammed422** [Chooloo/koler#375]
### Checklist

- [x] I am using the latest version - 1.4.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be great if you implement Material you or wallpaper theming in your app

Because then it will look like in contrast with android 12 UI

#### Is your feature request related to a problem? Please describe it

Now your app doesn't support material you or wallpaper theming both 

#### Additional context

My wallpaper
![Screenshot_20220320-234903_KISS launcher~01](https://user-images.githubusercontent.com/78704469/159176822-aea6d882-9690-4c0f-a037-60c9609220f4.png)

Material you compatible app
![Screenshot_20220320-234859_LSPosed](https://user-images.githubusercontent.com/78704469/159176850-9fcf786d-b46a-4e2b-af45-9b3d136bae4d.png)

#### How will you/everyone benefit from this feature?

By this feature other android 12 users can benefit like me

**Comment by DodoLeDev** [comment]
Hey! I think it could be a good idea to make Koler fit the current Material You theme! _And it doesn't look that difficult to implement it!_

But I think that the **entire app theming engine should be reviewed**, because it is currently poor in customization! 😅

Others also suggest adding blur background to the app! #206

**Comment by mikenrafter** [comment]
I'd love having this feature, as I frequently change my background, and other apps respond to this, but Koler doesn't.

**Comment by roeiedri** [comment]
The last version support Material U
