### ISSUE TITLE
duplication of letters and the inability to delete them when searching for a name

### ISSUE THREAD

**Issue by gentr** [Chooloo/koler#379]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info
 - Android version/Custom ROM version:
 - Device model: mi 11 lite android 12 miui 13
when i type a words to search a contact , gor example eg and to delete that words, i can not do it that and the words be more and more egegegegeg

**Comment by sonalder-darlene** [comment]
Not sure, but I might have the same issue.
Search in recent or contact double the letters I type and when trying to delete it adds more letters

**Comment by sonalder-darlene** [comment]
The title isn't clear. Should rename it something like : Dupplication of characters while typing and deleting

**Comment by Tobias-Lauerbach** [comment]
I have a similar bur when typing in phone numbers to call and then not being able to delete parts (makes duplicats)

**Comment by Perrin-the-wolf** [comment]
I have a similar Problem. It depends of which keyboard I`ve chosen. When I type something the suggestions from the keyboard will directly be used for searching even if I`m not choosing them. 
So I have to change the keyboard for koler to one without suggestions.

**Comment by gentr** [comment]
Like in previous comment issue is not in any keyboard, in Samsung  keyboard  this issue  not happen,  but in open board  keyboard  issue  is present.

**Comment by roeiedri** [comment]
Should be fixed, reopen if still happens
