### ISSUE TITLE
Auto Vibrate Mode

### ISSUE THREAD

**Issue by Lucejarv** [Chooloo/koler#38]
**Describe the bug**
After every time the call ends, The phone profile switches to vibrate only. Please fix this coz the rest of the app is amazing.

**Smartphone (please complete the following information):**
 - Devce: LG Q6 M700
 - OS: 8.1.0

**Comment by roeiedri** [comment]
Thank you very much for the feedback
As we wish we would have the time to solve this unfortunately we currently don't 
We hope you are still enjoying the app considering the problems

**Comment by roeiedri** [comment]
Were back!
About the issue... could you describe more?
The issue happens with no relation to anything?
Did you change the audio settings before the call?

**Comment by adityadhiman** [comment]
**Solution : 

In OngoingCallActivity Activity Replace ActionTime Class code with this**

class ActionTimer {

        CountDownTimer mTimer = null;
        boolean mIsRejecting = true;

        int oldVolume;

        private void setData(long millisInFuture, boolean isRejecting) {
            mIsRejecting = isRejecting;
            @ColorRes int textColorRes;
            @StringRes int textIndicator;
            if (isRejecting) {
                textColorRes = R.color.red_phone;
                textIndicator = R.string.reject_timer_indicator;
            } else {
                textColorRes = R.color.green_phone;
                textIndicator = R.string.answer_timer_indicator;
            }

            @ColorInt int textColor = ContextCompat.getColor(OngoingCallActivity.this, textColorRes);
            mActionTimeLeftText.setTextColor(textColor);
            mTimerIndicatorText.setText(textIndicator);

            mTimer = new CountDownTimer(millisInFuture, REFRESH_RATE) {
                Locale mLocale = Locale.getDefault();

                @Override
                public void onTick(long millisUntilFinished) {
                    int secondsUntilFinished = (int) (millisUntilFinished / 1000);
                    String timer = String.format(mLocale, "00:%02d", secondsUntilFinished);
                    mActionTimeLeftText.setText(timer);
                }

                @Override
                public void onFinish() {
                    end();
                }
            };
        }

        private void start() {
            mIsActionTimerEnable = true;
            oldVolume = mAudioManager.getStreamVolume(AudioManager.STREAM_RING);
            mAudioManager.setStreamVolume(AudioManager.STREAM_RING, 0, 0);
            if (mTimer != null) mTimer.start();
            else Timber.w("Couldn't start action timer (timer is null)");

            if (mActionTimerOverlay != null) setOverlay(mActionTimerOverlay);
        }

        private void cancel() {
            if (mTimer != null) mTimer.cancel();
            else Timber.w("Couldn't cancel action timer (timer is null)");

            finalEndCommonMan();
        }

        private void end() {
            if (mIsRejecting) endCall();
            else activateCall();

            finalEndCommonMan();
        }

        private void finalEndCommonMan() {
            mAudioManager.setStreamVolume(AudioManager.STREAM_RING, oldVolume, 0);
            removeOverlay();
        }
    }

**Comment by adityadhiman** [comment]
_**> Solution : 
> 
> In Activity OngoingCallActivity replace code of ActionTimer**_ 

    class ActionTimer {

        CountDownTimer mTimer = null;
        boolean mIsRejecting = true;
        boolean mIsActionTimerEnable = false;

        Integer oldVolume;

        private void setData(long millisInFuture, boolean isRejecting) {
            mIsRejecting = isRejecting;
            @ColorRes int textColorRes;
            @StringRes int textIndicator;
            if (isRejecting) {
                textColorRes = R.color.red_phone;
                textIndicator = R.string.reject_timer_indicator;
            } else {
                textColorRes = R.color.green_phone;
                textIndicator = R.string.answer_timer_indicator;
            }

            @ColorInt int textColor = ContextCompat.getColor(OngoingCallActivity.this, textColorRes);
            mActionTimeLeftText.setTextColor(textColor);
            mTimerIndicatorText.setText(textIndicator);

            mTimer = new CountDownTimer(millisInFuture, REFRESH_RATE) {
                Locale mLocale = Locale.getDefault();

                @Override
                public void onTick(long millisUntilFinished) {
                    int secondsUntilFinished = (int) (millisUntilFinished / 1000);
                    String timer = String.format(mLocale, "00:%02d", secondsUntilFinished);
                    mActionTimeLeftText.setText(timer);
                }

                @Override
                public void onFinish() {
                    end();
                }
            };
        }

        private void start() {
            mIsActionTimerEnable = true;
            oldVolume = mAudioManager.getStreamVolume(AudioManager.STREAM_RING);
            mAudioManager.setStreamVolume(AudioManager.STREAM_RING, 0, 0);
            if (mTimer != null) mTimer.start();
            else Timber.w("Couldn't start action timer (timer is null)");

            if (mActionTimerOverlay != null) setOverlay(mActionTimerOverlay);
        }

        private void cancel() {
            if (mTimer != null) mTimer.cancel();
            else Timber.w("Couldn't cancel action timer (timer is null)");

            finalEndCommonMan();
        }

        private void end() {
            if (mIsRejecting) endCall();
            else activateCall();

            finalEndCommonMan();
        }

        private void finalEndCommonMan() {
            if (mIsActionTimerEnable){
                mAudioManager.setStreamVolume(AudioManager.STREAM_RING, oldVolume, 0);
            }
            mIsActionTimerEnable = false;
            removeOverlay();
        }
    }

**Comment by roeiedri** [comment]
Thank you very much for helping, well add your solution and it'll be out in
the next update

**Comment by roeiedri** [comment]
Sorry for the insane delay, can u explain how does that code is responsible for fixing the issue 
Does the issue happens only when using call timer?
