### ISSUE TITLE
Koler dialer not working.

### ISSUE THREAD

**Issue by simanchal-45** [Chooloo/koler#385]
## Checklist

- [x] I am using the latest version - 1.4.3  
- [] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour
 It's open with system dialer. (Koler is my default app)

### Expected behavior
 Open with koler dialer.

### Device info
 - Android version/Custom ROM version: 8.1
 - Device model: Oppo A5s

https://user-images.githubusercontent.com/71957533/160586267-229dd9e3-bbb0-4256-b398-26518d4cd4eb.mp4

**Comment by roeiedri** [comment]
Its a crash
Do you have any way to record the traceback?

**Comment by simanchal-45** [comment]
Actually I don't know what traceback is:(

**Comment by joe733** [comment]
Seems like this is fixed in the updated version.
