### ISSUE TITLE
Copyed number deleting/edeting Bug 

### ISSUE THREAD

**Issue by Tobias-Lauerbach** [Chooloo/koler#386]
## Checklist

- [x] I am using the latest version - 1.4.3.75 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
(#379 is not the same but I have it too)
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

### Steps to reproduce the bug

1. Open the dilar
2. past a number into dilar
(first part of the bug appears: No Backspace/delete button or add-Contact at the bottom)
3. if you are now trying to ad a number by pressing any key the copied part will be deleted -> only added number left  

### Actual behavior

Not being able to Edit copied/pasted numbers in the dial-pad.

### Expected behavior

Being able to add numbers to pasted numbers and delete parts of it or add them as new Contacts

### Screenshots/Screen recordings

Not appearing buttons:
![Koler](https://user-images.githubusercontent.com/62332598/160682648-7964bb12-8429-4e41-ab92-db5099924593.png)

### Device info
 - Android version/Custom ROM version: CalyxOS 3.3.0 Android 12L
 - Device model: Google Pixel 5

**Comment by roeiedri** [comment]
Fixed
