### ISSUE TITLE
Menu items (titles) is blank in rtl languages

### ISSUE THREAD

**Issue by mojienjoyment** [Chooloo/koler#389]
- [x] I am using the latest version - 1.4.3
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

### Steps to reproduce the bug
When we switch to any right-to-left languages (like Persian,Arabic and others).. the menu item is blank and cant show any text (like Default pagesor others)... but it should show items! more information in screenshots...

### Screenshots/Screen recordings

![photo_2022-03-30_07-50-18](https://user-images.githubusercontent.com/68327458/160781176-0182e4d9-0128-48bb-9f2e-2a38dea8315f.jpg)

### Logs
any log

### Device info
 - Android version/Custom ROM version: MIUI 13 android 12
 - Device model: Poco x3 pro

**Comment by roeiedri** [comment]
Change to parsian and doesnt see this bug, probably got fixed.
