### ISSUE TITLE
Add open in WhatsApp

### ISSUE THREAD

**Issue by Pranab009** [Chooloo/koler#396]
### Checklist

- [x] I am using the latest version - 1.4.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Please add open in WhatsApp without saving number.
Recent call log to open in WhatsApp.

**Comment by roeiedri** [comment]
Added in 7a914e645bc4218473513a3d3c496e4ad950c510
