### ISSUE TITLE
Light theme can't work

### ISSUE THREAD

**Issue by Pranab009** [Chooloo/koler#402]
## Checklist

- [x] I am using the latest version - 1.4.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Can't show anything in light theme.

### Screenshots/Screen recordings

![Screenshot_20220407-223322](https://user-images.githubusercontent.com/65340361/162385742-68582748-96f6-4fce-9d74-06a52b70e612.png)

![Screenshot_20220407-223347](https://user-images.githubusercontent.com/65340361/162385748-33c09fac-0e76-4413-bbde-edfc5e41ea32.png)

### Device info
 - Android version/Custom ROM version: 10
 - Device model: in1

**Comment by roeiedri** [comment]
Fixed in GH-403
