### ISSUE TITLE
Dialer simulates unknown keypress when screen is auto-rotated

### ISSUE THREAD

**Issue by gitthepie** [Chooloo/koler#406]
I'm currently running Koler on Android 9. When I physically rotate my phone, a change in the screen orientation from portrait to landscape results in an audible keypad tone. If I'm on a phone menu that recognizes keypress inputs, the mere rotation is seen as an unknown input. The only workaround I know of is to disable auto-rotate while a phone call is active. Since screen rotation is unlikely to have been intended as input, I would classify this as a minor bug.

I don't know where the below checklist originally came from, but I've seen it in other bug reports, so I will use the same template:

**Checklist**
I am using the latest version - 1.4.3
I checked, but didn't find any duplicates (open OR closed) of this issue on Github.
This issue contains only one bug. I will open one issue for every bug report I want to file.

**Steps to reproduce the bug**
1. Dial any phone number
2. While the call is still ongoing, rotate the screen. A tone that sounds like a keypress will be audible.
3. Rotate the screen when an automated system prompts for keypad input to see that the rotation itself is recognize as input even though no keys have actually been pressed.

**Actual behavior**
When screen is rotated, an unknown keypress is simulated and a tone will be audible.

**Expected behavior**
No audible sound or submitted input on screen rotation.

**Logs**
To my knowledge, no logs were produced by the actual behavior.

**Device info**
Android version: 9

**Comment by roeiedri** [comment]
From what I see that's related to android's core phone functionality, you don't hear that beep in other dialers because they don't offer a landscape mode

**Comment by gitthepie** [comment]
Would it be possible to offer an option to disable auto rotate in the app itself? Auto rotate is handy in some apps (e.g. text/code editing with long lines). The rotation messes with menus that require number inputs in calls though.

**Comment by yephny** [comment]
I agree with @gitthepie , auto-rotate messes with this app, especially when on call.
