### ISSUE TITLE
App starts opening then suddenly closes

### ISSUE THREAD

**Issue by Resrcher** [Chooloo/koler#420]
## Checklist

- [x] I am using the latest version - 1.4.5 
- [] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

App starts to open, then suddenly closes

### Expected behavior

I expect the app to open and stay open until i close it.

### Screenshots/Screen recordings
 After several attempts to open the app, messae pops up saying, "Koler keeps closing" and has options to "App Info" or "Close app."
(Koler is set as the default phone app, and all permissions are enabled.)

### Logs
 No logs available.

### Device info
 - Android version/Custom ROM version: Android 9/ AssuranceROM Custom Stock(U693CL_01.02.05.220209)

 - Device model: Unimax U693CL

**Comment by roeiedri** [comment]
any error logs or tracebacks would be very very helpful :)

**Comment by Resrcher** [comment]
Sorry, phone not rooted.

------- Original Message -------

**Comment by roeiedri** [comment]
Not enough information, it can be anything.
Bug are being fixed so well probably get to this one eventually.
