### ISSUE TITLE
Merged call history

### ISSUE THREAD

**Issue by Pranab009** [Chooloo/koler#429]
## Checklist

- [x] I am using the latest version - 1.4.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/65340361/166250376-186dc073-614f-4a10-b690-bb3b48e53db9.mp4

### Device info
 - Android version/Custom ROM version:
 - Device model:

**Comment by Pranab009** [comment]
Already I do that.

**Comment by roeiedri** [comment]
Where's the issue? If you have a strike of recents from the same contact you'll see them as a group but if it's only one then it'll go straight to the recent.
