### ISSUE TITLE
Screen doesn't wake for incoming call if it's locked

### ISSUE THREAD

**Issue by SUJITHREDDY2314** [Chooloo/koler#433]
## Checklist

- [x] I am using the latest version - 1.4.5(https://github.com/Chooloo/koler/releases/tag/v1.4.5) 
- [] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Call your mobile using any other phone.
2. The lock screen stays blank unless you press the power button.

### Actual behaviour

The phone screen doesn't wake(when it is locked) for incoming calls. To lift the call, we have to press the power button.

### Expected behavior

The phone screen should wake(when it is locked) for incoming calls. 

### Device info
 - Android version/Custom ROM version: Android 11/MIUI Global 12.5.3 Stable
 - Device model: POCO M3

**Comment by Sewdohe** [comment]
I believe this could be fixed by a window flag, SHOW_WHEN_LOCKED or something like that, I saw it used in AOSP on a default app. I will try and investigate.

**Comment by Sewdohe** [comment]
like this:
mWindow.addFlags(
                | WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED
                | WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED);

**Comment by roeiedri** [comment]
Fixed
