### ISSUE TITLE
Feature Request please add indicator fast scroll, and add a system to block calls

### ISSUE THREAD

**Issue by qw123wh** [Chooloo/koler#44]
**Is your feature request related to a problem? Please describe.**
1 Hello, please you can add indicator fast scroll.
Most manufacturers: Xiaomi, samsung, huawei ... have a similar mechanism in their system apps

 It is more convenient to reach the contacts by clicking on the letter. 

2 Please add  a system to block calls

**Describe the solution you'd like**
Solution 1

https://github.com/reddit/IndicatorFastScroll

Solution 2 I do not know

**Comment by roeiedri** [comment]
By blocking calls u mean a list of numbers that the app would ignore?

**Comment by qw123wh** [comment]
"Block calls" I mean a "blacklist" to block those unwanted advertising calls, call centers, etc.

**Comment by roeiedri** [comment]
Got it.

**Comment by qw123wh** [comment]
Hi, I opened this problem a long time ago.  It's been a long time, will you implement these two functions?

**Comment by qw123wh** [comment]
I have separated the requests.  I close here and reopen in #123 and #124
