### ISSUE TITLE
G Maps phone number link doesn't work

### ISSUE THREAD

**Issue by MrComexs** [Chooloo/koler#441]
latest version - v1.4.6
    [] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
    [] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1.go to google maps and find a random place that has a phone number so koler can place a call

### Actual behavior
The koler app doesn't oepn, it makes a butch of inputs key sound but doesn't do anything (the app is still closed and send me to my home screen).

### Expected behavior
the phone number would be in the koler app so I can place a call.

### Device info
 LineageOS 19-20220506-NIGHTLY-beyond1lte
SM-G973F

**Comment by xdubx** [comment]
Same on Fairphone OS Android 11.

**Comment by roeiedri** [comment]
Fixed in latest commit
