### ISSUE TITLE
Can't get out of call history of a contact if choosen in recent tab

### ISSUE THREAD

**Issue by IvanKey1** [Chooloo/koler#448]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info
 - Android version/Custom ROM version:
 - Device model:

**Comment by Rov001** [comment]
I have same problem

**Comment by roeiedri** [comment]
Click outside of it
