### ISSUE TITLE
Call history not appear please fix it

### ISSUE THREAD

**Issue by Rov001** [Chooloo/koler#449]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info
 - Android version/Custom ROM version: Oxygenos 12.1 beta 1
 - Device model: OnePlus Nord 2 5g

**Comment by signed-log** [comment]
Can reproduce on v1.4.6 on Android 12 (Oppo CPH2025)

**Comment by roeiedri** [comment]
Probably permissions related issue, it's improved in next version
