### ISSUE TITLE
App crashes when clicking on links like tel:+14072380995

### ISSUE THREAD

**Issue by jhrush** [Chooloo/koler#456]
## Checklist

- [x] I am using the latest version - 1.4.6 
- [] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to web browser of choice
2. Click a telephone link
3. Android will state koler keeps stopping

### Actual behaviour

A rapid dial tone occurs and the app crashes

### Expected behavior

The phone number should be called

### Device info
 - Android version/Custom ROM version:
 - Device model:

Android 11

**Comment by elea11** [comment]
Same here on Android 12.1, protonAOSP, Pixel 4a 5G, microG.

Steps to reproduce: Click on a phone number in an SMS from the provider's mailbox, notifying about a missed call.

**Comment by Sewdohe** [comment]
Same issue here. I am going to try and diagnose this later tonight.

**Comment by Sewdohe** [comment]
Fixed [Here](https://github.com/Sewdohe/koler/commit/9e9dbde41525cd7c76eae9ccaa3ff1061df16736)

**Comment by DodoLeDev** [comment]
**Same problem here!**

But I just want to suggest another thing: could it be possible to remove the creepy sound made by the simultaneous dial tones of each number of the phone number? 😱
