### ISSUE TITLE
A feedback

### ISSUE THREAD

**Issue by soymadip** [Chooloo/koler#468]
Previous version's ui is far more better than latest one.

And sorry if this doesn't belong to bug(I couldn't decide in which catagory it belongs.)

**Comment by DodoLeDev** [comment]
I agree with you in some points...
But I personally think it's a needed step to pass, because this new ui will introduce better theming capabilities!

For me, it's just not *as polished as the previous version*, but I think the future will change your mind!

**Comment by soymadip** [comment]
> I agree with you in some points... But I personally think it's a needed step to pass, because this new ui will introduce better theming capabilities!
> 
> For me, it's just not _as polished as the previous version_, but I think the future will change your mind!

Yeah, I am looking forward to it

**Comment by soymadip** [comment]
Mi

**Comment by roeiedri** [comment]
Not an issue, the ui will not change back but will improve and will not stay exactly the same.
You are welcome to open a discussion regarding the ui :)
