### ISSUE TITLE
When copy country prefix app will crash/wont open at all

### ISSUE THREAD

**Issue by MatejPetrik007** [Chooloo/koler#471]
## Checklist

- [x] I am using the latest version - 1.5.0
- [X] I checked, but didn't find any duplicates 
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to Any site with the number with country prefix
2. Press on the number
3. the app crash or wont open the number
4. only working without the prefix

### Actual behaviour

https://user-images.githubusercontent.com/67949791/180672689-d0d9f718-6c3a-470e-9739-ae8fb3d36fa0.mp4

### Expected behavior
when i click on the number with prefix should work like the number without prefix

### Device info
 - Android version/Custom ROM version: A12, Linage OS 
 - Device model: One Plus A5000

**Comment by Horlacher** [comment]
probably the same bug as https://github.com/Chooloo/koler/issues/441
