### ISSUE TITLE
Show cached names in Recents

### ISSUE THREAD

**Issue by anuraag488** [Chooloo/koler#479]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
 Call log provides cached name column. Can you show cached name if it's present. I use a caller id app which adds cached name to call log.

**Comment by roeiedri** [comment]
Fixed
