### ISSUE TITLE
Wrong backspace button icon/symbol ⏎ should be ⌫ or ←

### ISSUE THREAD

**Issue by ph00lt0** [Chooloo/koler#486]
## Checklist

- [x] I am using the latest version - 1.5
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

The dial pad's backspace button uses an 'enter' symbol. A backspace icon is an arrow from the right to the left ← or  preferably delete ⌫. The current ⏎ is reserved for enter/submit actions and therefore is rather confusing.

**Comment by roeiedri** [comment]
Fixed in latest commit
