### ISSUE TITLE
Koler is not responding when call a number by selecting the number in the browser (Chrome and Firefox)

### ISSUE THREAD

**Issue by r00t34** [Chooloo/koler#487]
## Checklist

- [x] I am using the latest version - 1.5.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

I am selecting phone number from browser (Chrome and Firefox) and selecting Call button and Koler is not responding and closing itself. I tried several times and Koler is not responding and i can't call a number from copied phone number from browser. This is bad because you need keep in mind for call a number from browser.

### Expected behavior

We can call phone numbers from browsers by selecting phone number by selecting phone number.

### Device info
 - Android version/Custom ROM version: Android 12 stock ROM
 - Device model: Mi Note 10 Lite

**Comment by xdubx** [comment]
It seems the same bug as https://github.com/Chooloo/koler/issues/441

**Comment by roeiedri** [comment]
Fixed in latest commit, will be in next release
