### ISSUE TITLE
Can not delete call log from Recents

### ISSUE THREAD

**Issue by r00t34** [Chooloo/koler#488]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Go to Recents and try delete one of the call logs you will not delete because Koler is not deleting call logs from Recent.

### Actual behaviour

Can not delete call logs from Recent

### Expected behavior

We should able to delete call logs like other every dialer app

### Device info
 - Android version/Custom ROM version: Android 12 (Stock ROM)
 - Device model: Mi Note 10 Lite

**Comment by stevencook66** [comment]
Same issue for me. Pixel 6 Pro/Android 13 stock.

**Comment by roeiedri** [comment]
Fixed in a recent commit, will be available in the next release
