### ISSUE TITLE
Recents causes app crash

### ISSUE THREAD

**Issue by RawkFist20** [Chooloo/koler#491]
If you set the Recents as the default page, the app crashes. It happens when trying to access the Recents when Contacts is the default page as well. 
Android 12 OnePlus9

**Comment by roeiedri** [comment]
Any crash log? I cant reproduce the bug

**Comment by roeiedri** [comment]
Closed for inactivity, reopen if still happens

**Comment by Nive9** [comment]
Got that same issue as well. Opening Recents just crashes the app. Does the [logcat](https://gist.github.com/Nive9/a47bc7fb5384e6f5cb427f0d6c0b9653) help?

If there's anything more you need, let me know. 

Device:
* OnePlus 8T
* Android 13
* Koler v1.6.0 (PlayStore) | v1.4.5 / 1.4.6 / 1.5.0 (F-Droid)
