### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [Chooloo/koler#509]
https://monitor.f-droid.org/builds/log/com.chooloo.www.koler/80#site-footer

Is jdk 18 required? Currently only jdk 17 is available in Debian stable. And jdk 18 is EOL.

**Comment by abusayed0206** [comment]
Also, not updated in playstore build.

**Comment by yephny** [comment]
Any updates?

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/commit/970e8553cffab22d7d24a4baf0f3f77a7216a369

**Comment by yephny** [comment]
Any news?

**Comment by linsui** [comment]
It turns out that jdk 18 is not needed at all...
