### ISSUE TITLE
Group similar recents not working properly

### ISSUE THREAD

**Issue by itsmmt305** [Chooloo/koler#511]
## Checklist

- [x] I am using the latest version - 1.6.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to ellipses menu
2. Press on group similar recents and select yes/yap(?)
3. try to open a recent call from list after restarting the app
--> 

### Actual behaviour

the whole call history from the day is clubbed together

![Screenshot_2023-02-27-16-01-56-852_com chooloo www koler~2](https://user-images.githubusercontent.com/94820934/221541403-1e7e8576-9e2e-4a5e-ae91-24528de2dec0.jpg)

### Expected behavior

similar recents must be grouped i.e. from the same phone number as in previous versions

![Screenshot_2023-02-27-16-05-41-557_com chooloo www koler~2](https://user-images.githubusercontent.com/94820934/221541773-c31efa43-fc5c-4dbb-ad3a-b1c1496dd08e.jpg)

### Device info
 - OS: Android 12/MIUI 13.0.3
 - Device: Redmi 10

**Comment by roeiedri** [comment]
Fixed in 5bed0c2c0db0bab28146e479a3cc72377faee285

**Comment by itsmmt305** [comment]
yayayyyyyyyt
