### ISSUE TITLE
Recent calls menu error

### ISSUE THREAD

**Issue by ViktorKahu** [Chooloo/koler#514]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to recent calls
2. Press on any number that isn't saved in your contacts

### Actual behaviour

Instead of going into options to call/text/etc..., a secondary menu opens to prompt you to select the contact again.

### Expected behavior

The correct call options menu, not a secondary list.

### Screenshots/Screen recordings

![Screenshot_20230312-163235~2](https://user-images.githubusercontent.com/125934998/224526615-c881517b-9698-4a77-abe4-019137af8de9.png)
![Screenshot_20230312-163241~2](https://user-images.githubusercontent.com/125934998/224526620-ec9777bc-ba05-418f-81cf-cec8056d3126.png)

### Device info
 - Android 13 GrapheneOS
 - Device model: Pixel 7 pro

**Comment by roeiedri** [comment]
Fixed in latest commit, it should indeed show a list of number but rather the history of that specific number and not all the recents.
