### ISSUE TITLE
Screen does not lock during call when using the ear piece.

### ISSUE THREAD

**Issue by ViktorKahu** [Chooloo/koler#517]
## Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Initiate or answer a call.
2. Hold the phone to your ear.

### Actual behaviour

Buttons get pressed with your face/cheek, pausing the call or initiating other actions.

### Expected behavior

Phone to recognize that you are using the ear piece (via camera) and lock buttons, until the phone is held away from the face.

### Device info
 - Android version/Custom ROM version: Android 13/GrapheneOS
 - Device model: Pixel 7 Pro.

**Comment by roeiedri** [comment]
Should work now

**Comment by ViktorKahu** [comment]
Just out of curiosity, how can something function differently if nothing has changed (no update since issue was raised)?
