### ISSUE TITLE
infinit loading from ConnectYou 

### ISSUE THREAD

**Issue by RemyBorius** [Chooloo/koler#519]
## Checklist

- [x] I am using the latest version - 1.6.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Install ConnectYou contact app
2. Open and select a contact
3. Call the contact from ConnectYou

### Actual behaviour

Infinit loadind

### Expected behavior

Loading ends

### Logs

No logs 

### Device info
 - Android version/Custom ROM version: android 11 / dotos5.2
 - Device model: samsung s10e (exynos chip) SM-G970F

**Comment by RemyBorius** [comment]
Actually, it's the same problem as #520

**Comment by roeiedri** [comment]
Duplicated
