### ISSUE TITLE
Goes immediately to voicemail when screen is locked 

### ISSUE THREAD

**Issue by BioRider17** [Chooloo/koler#525]
## Checklist

- [x] I am using the latest version - 1.6.0
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Call phone from another phone
2. Have screen locked on the phone with Koler installed

### Actual behaviour

Call not recieved

### Expected behavior

Able to answer call.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/110435075/234712925-d7c0f901-fdcc-4e64-8334-c8c9f80803c5.mp4

### Logs

[Koler.txt](https://github.com/Chooloo/koler/files/11337647/Koler.txt)

### Device info
 - Android version/Custom ROM version: LineageOS 20.0/ Android 13
 - Device model: River

**Comment by roeiedri** [comment]
That didn't happen on every phone i have tried it with.
Can you elaborate on when that happens to you? and did you try with a different phone?

**Comment by BioRider17** [comment]
Closing, turns out I'm an idiot and had airplane mode on.
