### ISSUE TITLE
DELETE CALL LOGS 

### ISSUE THREAD

**Issue by Twiub** [Chooloo/koler#61]
I have seen your can delete call log one by one only. 
Add ability to delete maltiple logs at once, delete all call log from one number and also delete all phone call log at once. 

This is for user privacy reasons

**Comment by roeiedri** [comment]
If you're interested I've started a new branch for selectable items.
After working on it for couple of hours, I did some work but I currently don't have much time to work on this feature :( (it's a big one).
So for now if someone pushes a pull request or something that would be helpful.
Other than that, it might take some time.
