### ISSUE TITLE
App stuck when input phone number

### ISSUE THREAD

**Issue by cgwang1580** [Chooloo/koler#72]
I clone code of master branch with log_5b2b8cd，and build the app, when input the third number at dial interface, the app stucked, is it a bug of code?

**Comment by roeiedri** [comment]
Can u elaborate more about this issue? When i try to do the same thing, everything works great

**Comment by strel** [comment]
Here too.
Mi A2 Lite, Android 10. It happens to me on 0.5.3 and 0.5.2 but not on 0.5.1

**Comment by roeiedri** [comment]
First of all thank you for taking the time to elaborate
Can you send the format of the phone number in your area? The problem isn't occurring with my version so I'm guessing it's related to the app trying to format the number by area format

**Comment by strel** [comment]
https://www.temporary-url.com/B44A7
Now I'm facing another issue (probably not related with the app). After several uninstall-reinstall cycles something went wrong with my Mi A2 Lite and now switching to speaker while making a call isn't working with any koler version I install. Don't Know exactly at what point happened.
