### ISSUE TITLE
Always ask SIM 

### ISSUE THREAD

**Issue by ze0ss** [Chooloo/koler#81]
Please add an option to select the SIM everytime I place a call, currently it is either of the SIM present in the phone.

Alternatives - As seen in the Google Dialler

**Comment by talusannni** [comment]
I have the same problem,
My App working in 99 % mobiles, but in Vivo s1 call is not going through due to sim selection problem.
If I set a Default SIM in device settings, it is working.

**Comment by roeiedri** [comment]
@ze0ss @talusannni 
Could you be a tester for the selectable sim feature? I cant emulate multiple sim so i need someone to test it :)
