### ISSUE TITLE
Contacts with same number are not shown as different contacts in Recents screen

### ISSUE THREAD

**Issue by zhirzh** [Chooloo/koler#97]
**Describe the bug**
Contacts with same number are not shown as different contacts in Recents screen

**To Reproduce**
1. Create multiple contacts with same number (in the gif, _Su_ & _Su2_) and call them
1. In the Recents screen, all call logs are shown for a single contact (in the gif, _Su_)

**Expected behavior**
Each contact's call logs should be shown separately even though their numbers are the same

**Screenshots**

<img width="400" src="https://user-images.githubusercontent.com/8132723/94449854-2cb4cc80-01ca-11eb-9126-b2107d2544b2.gif" />

**Comment by roeiedri** [comment]
Sorry I didn't quite understand, it's already showing a call log for every call separately
So where's the problem?

**Comment by zhirzh** [comment]
In the gif above, I called "su2" but Recents screen only shows "su" when it should show "su2" for the last call.
